// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: marketing.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMarketingCreateCoupon = "/platform.marketing_service.v1.Marketing/CreateCoupon"
const OperationMarketingDeleteCoupon = "/platform.marketing_service.v1.Marketing/DeleteCoupon"
const OperationMarketingGetCoupon = "/platform.marketing_service.v1.Marketing/GetCoupon"
const OperationMarketingGetCouponStats = "/platform.marketing_service.v1.Marketing/GetCouponStats"
const OperationMarketingGetCouponsSummaryStats = "/platform.marketing_service.v1.Marketing/GetCouponsSummaryStats"
const OperationMarketingListCouponUsages = "/platform.marketing_service.v1.Marketing/ListCouponUsages"
const OperationMarketingListCoupons = "/platform.marketing_service.v1.Marketing/ListCoupons"
const OperationMarketingUpdateCoupon = "/platform.marketing_service.v1.Marketing/UpdateCoupon"
const OperationMarketingUseCoupon = "/platform.marketing_service.v1.Marketing/UseCoupon"
const OperationMarketingValidateCoupon = "/platform.marketing_service.v1.Marketing/ValidateCoupon"

type MarketingHTTPServer interface {
	// CreateCoupon ========== Coupon Management API (供开发者控制台使用) ==========
	// CreateCoupon 创建优惠券
	CreateCoupon(context.Context, *CreateCouponRequest) (*CreateCouponReply, error)
	// DeleteCoupon DeleteCoupon 删除优惠券
	DeleteCoupon(context.Context, *DeleteCouponRequest) (*DeleteCouponReply, error)
	// GetCoupon GetCoupon 获取优惠券
	GetCoupon(context.Context, *GetCouponRequest) (*GetCouponReply, error)
	// GetCouponStats GetCouponStats 获取优惠券统计
	GetCouponStats(context.Context, *GetCouponStatsRequest) (*GetCouponStatsReply, error)
	// GetCouponsSummaryStats GetCouponsSummaryStats 获取所有优惠券汇总统计（供营销效果仪表板使用）
	GetCouponsSummaryStats(context.Context, *GetCouponsSummaryStatsRequest) (*GetCouponsSummaryStatsReply, error)
	// ListCouponUsages ListCouponUsages 列出优惠券使用记录
	ListCouponUsages(context.Context, *ListCouponUsagesRequest) (*ListCouponUsagesReply, error)
	// ListCoupons ListCoupons 列出优惠券
	ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsReply, error)
	// UpdateCoupon UpdateCoupon 更新优惠券
	UpdateCoupon(context.Context, *UpdateCouponRequest) (*UpdateCouponReply, error)
	// UseCoupon UseCoupon 使用优惠券 (供 Payment Service 调用)
	UseCoupon(context.Context, *UseCouponRequest) (*UseCouponReply, error)
	// ValidateCoupon ValidateCoupon 验证优惠券 (供 Payment Service 调用)
	ValidateCoupon(context.Context, *ValidateCouponRequest) (*ValidateCouponReply, error)
}

func RegisterMarketingHTTPServer(s *http.Server, srv MarketingHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/coupons", _Marketing_CreateCoupon0_HTTP_Handler(srv))
	r.GET("/v1/coupons/{code}", _Marketing_GetCoupon0_HTTP_Handler(srv))
	r.GET("/v1/coupons", _Marketing_ListCoupons0_HTTP_Handler(srv))
	r.PUT("/v1/coupons/{code}", _Marketing_UpdateCoupon0_HTTP_Handler(srv))
	r.DELETE("/v1/coupons/{code}", _Marketing_DeleteCoupon0_HTTP_Handler(srv))
	r.POST("/v1/coupons/validate", _Marketing_ValidateCoupon0_HTTP_Handler(srv))
	r.POST("/v1/coupons/use", _Marketing_UseCoupon0_HTTP_Handler(srv))
	r.GET("/v1/coupons/{code}/stats", _Marketing_GetCouponStats0_HTTP_Handler(srv))
	r.GET("/v1/coupons/{code}/usages", _Marketing_ListCouponUsages0_HTTP_Handler(srv))
	r.GET("/v1/coupons/summary-stats", _Marketing_GetCouponsSummaryStats0_HTTP_Handler(srv))
}

func _Marketing_CreateCoupon0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCouponRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingCreateCoupon)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCoupon(ctx, req.(*CreateCouponRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCouponReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetCoupon0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCouponRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetCoupon)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCoupon(ctx, req.(*GetCouponRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCouponReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListCoupons0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCouponsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListCoupons)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCoupons(ctx, req.(*ListCouponsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCouponsReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_UpdateCoupon0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCouponRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingUpdateCoupon)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCoupon(ctx, req.(*UpdateCouponRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCouponReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_DeleteCoupon0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCouponRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingDeleteCoupon)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCoupon(ctx, req.(*DeleteCouponRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCouponReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ValidateCoupon0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ValidateCouponRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingValidateCoupon)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ValidateCoupon(ctx, req.(*ValidateCouponRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ValidateCouponReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_UseCoupon0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UseCouponRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingUseCoupon)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UseCoupon(ctx, req.(*UseCouponRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UseCouponReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetCouponStats0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCouponStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetCouponStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCouponStats(ctx, req.(*GetCouponStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCouponStatsReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListCouponUsages0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCouponUsagesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListCouponUsages)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCouponUsages(ctx, req.(*ListCouponUsagesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCouponUsagesReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetCouponsSummaryStats0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCouponsSummaryStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetCouponsSummaryStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCouponsSummaryStats(ctx, req.(*GetCouponsSummaryStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCouponsSummaryStatsReply)
		return ctx.Result(200, reply)
	}
}

type MarketingHTTPClient interface {
	// CreateCoupon ========== Coupon Management API (供开发者控制台使用) ==========
	// CreateCoupon 创建优惠券
	CreateCoupon(ctx context.Context, req *CreateCouponRequest, opts ...http.CallOption) (rsp *CreateCouponReply, err error)
	// DeleteCoupon DeleteCoupon 删除优惠券
	DeleteCoupon(ctx context.Context, req *DeleteCouponRequest, opts ...http.CallOption) (rsp *DeleteCouponReply, err error)
	// GetCoupon GetCoupon 获取优惠券
	GetCoupon(ctx context.Context, req *GetCouponRequest, opts ...http.CallOption) (rsp *GetCouponReply, err error)
	// GetCouponStats GetCouponStats 获取优惠券统计
	GetCouponStats(ctx context.Context, req *GetCouponStatsRequest, opts ...http.CallOption) (rsp *GetCouponStatsReply, err error)
	// GetCouponsSummaryStats GetCouponsSummaryStats 获取所有优惠券汇总统计（供营销效果仪表板使用）
	GetCouponsSummaryStats(ctx context.Context, req *GetCouponsSummaryStatsRequest, opts ...http.CallOption) (rsp *GetCouponsSummaryStatsReply, err error)
	// ListCouponUsages ListCouponUsages 列出优惠券使用记录
	ListCouponUsages(ctx context.Context, req *ListCouponUsagesRequest, opts ...http.CallOption) (rsp *ListCouponUsagesReply, err error)
	// ListCoupons ListCoupons 列出优惠券
	ListCoupons(ctx context.Context, req *ListCouponsRequest, opts ...http.CallOption) (rsp *ListCouponsReply, err error)
	// UpdateCoupon UpdateCoupon 更新优惠券
	UpdateCoupon(ctx context.Context, req *UpdateCouponRequest, opts ...http.CallOption) (rsp *UpdateCouponReply, err error)
	// UseCoupon UseCoupon 使用优惠券 (供 Payment Service 调用)
	UseCoupon(ctx context.Context, req *UseCouponRequest, opts ...http.CallOption) (rsp *UseCouponReply, err error)
	// ValidateCoupon ValidateCoupon 验证优惠券 (供 Payment Service 调用)
	ValidateCoupon(ctx context.Context, req *ValidateCouponRequest, opts ...http.CallOption) (rsp *ValidateCouponReply, err error)
}

type MarketingHTTPClientImpl struct {
	cc *http.Client
}

func NewMarketingHTTPClient(client *http.Client) MarketingHTTPClient {
	return &MarketingHTTPClientImpl{client}
}

// CreateCoupon ========== Coupon Management API (供开发者控制台使用) ==========
// CreateCoupon 创建优惠券
func (c *MarketingHTTPClientImpl) CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...http.CallOption) (*CreateCouponReply, error) {
	var out CreateCouponReply
	pattern := "/v1/coupons"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingCreateCoupon))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteCoupon DeleteCoupon 删除优惠券
func (c *MarketingHTTPClientImpl) DeleteCoupon(ctx context.Context, in *DeleteCouponRequest, opts ...http.CallOption) (*DeleteCouponReply, error) {
	var out DeleteCouponReply
	pattern := "/v1/coupons/{code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingDeleteCoupon))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCoupon GetCoupon 获取优惠券
func (c *MarketingHTTPClientImpl) GetCoupon(ctx context.Context, in *GetCouponRequest, opts ...http.CallOption) (*GetCouponReply, error) {
	var out GetCouponReply
	pattern := "/v1/coupons/{code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetCoupon))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCouponStats GetCouponStats 获取优惠券统计
func (c *MarketingHTTPClientImpl) GetCouponStats(ctx context.Context, in *GetCouponStatsRequest, opts ...http.CallOption) (*GetCouponStatsReply, error) {
	var out GetCouponStatsReply
	pattern := "/v1/coupons/{code}/stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetCouponStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCouponsSummaryStats GetCouponsSummaryStats 获取所有优惠券汇总统计（供营销效果仪表板使用）
func (c *MarketingHTTPClientImpl) GetCouponsSummaryStats(ctx context.Context, in *GetCouponsSummaryStatsRequest, opts ...http.CallOption) (*GetCouponsSummaryStatsReply, error) {
	var out GetCouponsSummaryStatsReply
	pattern := "/v1/coupons/summary-stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetCouponsSummaryStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCouponUsages ListCouponUsages 列出优惠券使用记录
func (c *MarketingHTTPClientImpl) ListCouponUsages(ctx context.Context, in *ListCouponUsagesRequest, opts ...http.CallOption) (*ListCouponUsagesReply, error) {
	var out ListCouponUsagesReply
	pattern := "/v1/coupons/{code}/usages"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListCouponUsages))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCoupons ListCoupons 列出优惠券
func (c *MarketingHTTPClientImpl) ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...http.CallOption) (*ListCouponsReply, error) {
	var out ListCouponsReply
	pattern := "/v1/coupons"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListCoupons))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCoupon UpdateCoupon 更新优惠券
func (c *MarketingHTTPClientImpl) UpdateCoupon(ctx context.Context, in *UpdateCouponRequest, opts ...http.CallOption) (*UpdateCouponReply, error) {
	var out UpdateCouponReply
	pattern := "/v1/coupons/{code}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingUpdateCoupon))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UseCoupon UseCoupon 使用优惠券 (供 Payment Service 调用)
func (c *MarketingHTTPClientImpl) UseCoupon(ctx context.Context, in *UseCouponRequest, opts ...http.CallOption) (*UseCouponReply, error) {
	var out UseCouponReply
	pattern := "/v1/coupons/use"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingUseCoupon))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ValidateCoupon ValidateCoupon 验证优惠券 (供 Payment Service 调用)
func (c *MarketingHTTPClientImpl) ValidateCoupon(ctx context.Context, in *ValidateCouponRequest, opts ...http.CallOption) (*ValidateCouponReply, error) {
	var out ValidateCouponReply
	pattern := "/v1/coupons/validate"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingValidateCoupon))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
