// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.9.0
// - protoc             v6.33.1
// source: marketing.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMarketingAddTaskToCampaign = "/platform.marketing_service.v1.Marketing/AddTaskToCampaign"
const OperationMarketingAssignRedeemCode = "/platform.marketing_service.v1.Marketing/AssignRedeemCode"
const OperationMarketingCancelInventory = "/platform.marketing_service.v1.Marketing/CancelInventory"
const OperationMarketingConfirmInventory = "/platform.marketing_service.v1.Marketing/ConfirmInventory"
const OperationMarketingCreateAudience = "/platform.marketing_service.v1.Marketing/CreateAudience"
const OperationMarketingCreateCampaign = "/platform.marketing_service.v1.Marketing/CreateCampaign"
const OperationMarketingCreateReward = "/platform.marketing_service.v1.Marketing/CreateReward"
const OperationMarketingCreateTask = "/platform.marketing_service.v1.Marketing/CreateTask"
const OperationMarketingDeleteAudience = "/platform.marketing_service.v1.Marketing/DeleteAudience"
const OperationMarketingDeleteCampaign = "/platform.marketing_service.v1.Marketing/DeleteCampaign"
const OperationMarketingDeleteReward = "/platform.marketing_service.v1.Marketing/DeleteReward"
const OperationMarketingDeleteTask = "/platform.marketing_service.v1.Marketing/DeleteTask"
const OperationMarketingGenerateRedeemCodes = "/platform.marketing_service.v1.Marketing/GenerateRedeemCodes"
const OperationMarketingGetAudience = "/platform.marketing_service.v1.Marketing/GetAudience"
const OperationMarketingGetCampaign = "/platform.marketing_service.v1.Marketing/GetCampaign"
const OperationMarketingGetRedeemCode = "/platform.marketing_service.v1.Marketing/GetRedeemCode"
const OperationMarketingGetReward = "/platform.marketing_service.v1.Marketing/GetReward"
const OperationMarketingGetRewardGrant = "/platform.marketing_service.v1.Marketing/GetRewardGrant"
const OperationMarketingGetTask = "/platform.marketing_service.v1.Marketing/GetTask"
const OperationMarketingGetTaskCompletionStats = "/platform.marketing_service.v1.Marketing/GetTaskCompletionStats"
const OperationMarketingListAudiences = "/platform.marketing_service.v1.Marketing/ListAudiences"
const OperationMarketingListCampaignTasks = "/platform.marketing_service.v1.Marketing/ListCampaignTasks"
const OperationMarketingListCampaigns = "/platform.marketing_service.v1.Marketing/ListCampaigns"
const OperationMarketingListInventoryReservations = "/platform.marketing_service.v1.Marketing/ListInventoryReservations"
const OperationMarketingListRedeemCodes = "/platform.marketing_service.v1.Marketing/ListRedeemCodes"
const OperationMarketingListRewardGrants = "/platform.marketing_service.v1.Marketing/ListRewardGrants"
const OperationMarketingListRewards = "/platform.marketing_service.v1.Marketing/ListRewards"
const OperationMarketingListTaskCompletionLogs = "/platform.marketing_service.v1.Marketing/ListTaskCompletionLogs"
const OperationMarketingListTasks = "/platform.marketing_service.v1.Marketing/ListTasks"
const OperationMarketingListTasksByCampaign = "/platform.marketing_service.v1.Marketing/ListTasksByCampaign"
const OperationMarketingRedeemCode = "/platform.marketing_service.v1.Marketing/RedeemCode"
const OperationMarketingRemoveTaskFromCampaign = "/platform.marketing_service.v1.Marketing/RemoveTaskFromCampaign"
const OperationMarketingReserveInventory = "/platform.marketing_service.v1.Marketing/ReserveInventory"
const OperationMarketingTriggerTaskEvent = "/platform.marketing_service.v1.Marketing/TriggerTaskEvent"
const OperationMarketingUpdateAudience = "/platform.marketing_service.v1.Marketing/UpdateAudience"
const OperationMarketingUpdateCampaign = "/platform.marketing_service.v1.Marketing/UpdateCampaign"
const OperationMarketingUpdateReward = "/platform.marketing_service.v1.Marketing/UpdateReward"
const OperationMarketingUpdateRewardGrantStatus = "/platform.marketing_service.v1.Marketing/UpdateRewardGrantStatus"
const OperationMarketingUpdateTask = "/platform.marketing_service.v1.Marketing/UpdateTask"

type MarketingHTTPServer interface {
	// AddTaskToCampaign ========== Campaign Task Management API ==========
	// AddTaskToCampaign 将任务添加到活动
	AddTaskToCampaign(context.Context, *AddTaskToCampaignRequest) (*AddTaskToCampaignReply, error)
	// AssignRedeemCode AssignRedeemCode 分配兑换码
	AssignRedeemCode(context.Context, *AssignRedeemCodeRequest) (*AssignRedeemCodeReply, error)
	// CancelInventory CancelInventory 取消库存
	CancelInventory(context.Context, *CancelInventoryRequest) (*CancelInventoryReply, error)
	// ConfirmInventory ConfirmInventory 确认库存
	ConfirmInventory(context.Context, *ConfirmInventoryRequest) (*ConfirmInventoryReply, error)
	// CreateAudience ========== Audience API ==========
	// CreateAudience 创建受众
	CreateAudience(context.Context, *CreateAudienceRequest) (*CreateAudienceReply, error)
	// CreateCampaign CreateCampaign 创建营销活动
	CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignReply, error)
	// CreateReward ========== Reward API ==========
	// CreateReward 创建奖励
	CreateReward(context.Context, *CreateRewardRequest) (*CreateRewardReply, error)
	// CreateTask ========== Task API ==========
	// CreateTask 创建任务
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskReply, error)
	// DeleteAudience DeleteAudience 删除受众
	DeleteAudience(context.Context, *DeleteAudienceRequest) (*DeleteAudienceReply, error)
	// DeleteCampaign DeleteCampaign 删除营销活动
	DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignReply, error)
	// DeleteReward DeleteReward 删除奖励
	DeleteReward(context.Context, *DeleteRewardRequest) (*DeleteRewardReply, error)
	// DeleteTask DeleteTask 删除任务
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskReply, error)
	// GenerateRedeemCodes GenerateRedeemCodes 生成兑换码
	GenerateRedeemCodes(context.Context, *GenerateRedeemCodesRequest) (*GenerateRedeemCodesReply, error)
	// GetAudience GetAudience 获取受众
	GetAudience(context.Context, *GetAudienceRequest) (*GetAudienceReply, error)
	// GetCampaign GetCampaign 获取营销活动
	GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignReply, error)
	// GetRedeemCode GetRedeemCode 获取兑换码
	GetRedeemCode(context.Context, *GetRedeemCodeRequest) (*GetRedeemCodeReply, error)
	// GetReward GetReward 获取奖励
	GetReward(context.Context, *GetRewardRequest) (*GetRewardReply, error)
	// GetRewardGrant GetRewardGrant 获取奖励发放记录
	GetRewardGrant(context.Context, *GetRewardGrantRequest) (*GetRewardGrantReply, error)
	// GetTask GetTask 获取任务
	GetTask(context.Context, *GetTaskRequest) (*GetTaskReply, error)
	// GetTaskCompletionStats GetTaskCompletionStats 获取任务完成统计
	GetTaskCompletionStats(context.Context, *GetTaskCompletionStatsRequest) (*GetTaskCompletionStatsReply, error)
	// ListAudiences ListAudiences 列出受众
	ListAudiences(context.Context, *ListAudiencesRequest) (*ListAudiencesReply, error)
	// ListCampaignTasks ListCampaignTasks 列出活动的所有任务
	ListCampaignTasks(context.Context, *ListCampaignTasksRequest) (*ListCampaignTasksReply, error)
	// ListCampaigns ListCampaigns 列出营销活动
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsReply, error)
	// ListInventoryReservations ListInventoryReservations 列出库存预占记录
	ListInventoryReservations(context.Context, *ListInventoryReservationsRequest) (*ListInventoryReservationsReply, error)
	// ListRedeemCodes ListRedeemCodes 列出兑换码
	ListRedeemCodes(context.Context, *ListRedeemCodesRequest) (*ListRedeemCodesReply, error)
	// ListRewardGrants ========== RewardGrant API ==========
	// ListRewardGrants 列出奖励发放记录
	ListRewardGrants(context.Context, *ListRewardGrantsRequest) (*ListRewardGrantsReply, error)
	// ListRewards ListRewards 列出奖励
	ListRewards(context.Context, *ListRewardsRequest) (*ListRewardsReply, error)
	// ListTaskCompletionLogs ========== Task Completion Log API ==========
	// ListTaskCompletionLogs 列出任务完成日志
	ListTaskCompletionLogs(context.Context, *ListTaskCompletionLogsRequest) (*ListTaskCompletionLogsReply, error)
	// ListTasks ListTasks 列出任务
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error)
	// ListTasksByCampaign ListTasksByCampaign 根据活动列出任务
	ListTasksByCampaign(context.Context, *ListTasksByCampaignRequest) (*ListTasksByCampaignReply, error)
	// RedeemCode RedeemCode 兑换码核销
	RedeemCode(context.Context, *RedeemCodeRequest) (*RedeemCodeReply, error)
	// RemoveTaskFromCampaign RemoveTaskFromCampaign 从活动中移除任务
	RemoveTaskFromCampaign(context.Context, *RemoveTaskFromCampaignRequest) (*RemoveTaskFromCampaignReply, error)
	// ReserveInventory ========== Inventory Management API ==========
	// ReserveInventory 预占库存
	ReserveInventory(context.Context, *ReserveInventoryRequest) (*ReserveInventoryReply, error)
	// TriggerTaskEvent ========== Task Event API ==========
	// TriggerTaskEvent 触发任务事件
	TriggerTaskEvent(context.Context, *TriggerTaskEventRequest) (*TriggerTaskEventReply, error)
	// UpdateAudience UpdateAudience 更新受众
	UpdateAudience(context.Context, *UpdateAudienceRequest) (*UpdateAudienceReply, error)
	// UpdateCampaign UpdateCampaign 更新营销活动
	UpdateCampaign(context.Context, *UpdateCampaignRequest) (*UpdateCampaignReply, error)
	// UpdateReward UpdateReward 更新奖励
	UpdateReward(context.Context, *UpdateRewardRequest) (*UpdateRewardReply, error)
	// UpdateRewardGrantStatus UpdateRewardGrantStatus 更新发放状态
	UpdateRewardGrantStatus(context.Context, *UpdateRewardGrantStatusRequest) (*UpdateRewardGrantStatusReply, error)
	// UpdateTask UpdateTask 更新任务
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskReply, error)
}

func RegisterMarketingHTTPServer(s *http.Server, srv MarketingHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/campaigns", _Marketing_CreateCampaign0_HTTP_Handler(srv))
	r.GET("/v1/campaigns/{campaign_id}", _Marketing_GetCampaign0_HTTP_Handler(srv))
	r.GET("/v1/campaigns", _Marketing_ListCampaigns0_HTTP_Handler(srv))
	r.PUT("/v1/campaigns/{campaign_id}", _Marketing_UpdateCampaign0_HTTP_Handler(srv))
	r.DELETE("/v1/campaigns/{campaign_id}", _Marketing_DeleteCampaign0_HTTP_Handler(srv))
	r.POST("/v1/campaigns/{campaign_id}/redeem-codes", _Marketing_GenerateRedeemCodes0_HTTP_Handler(srv))
	r.POST("/v1/redeem", _Marketing_RedeemCode0_HTTP_Handler(srv))
	r.POST("/v1/redeem-codes/{code}/assign", _Marketing_AssignRedeemCode0_HTTP_Handler(srv))
	r.GET("/v1/redeem-codes", _Marketing_ListRedeemCodes0_HTTP_Handler(srv))
	r.GET("/v1/redeem-codes/{code}", _Marketing_GetRedeemCode0_HTTP_Handler(srv))
	r.POST("/v1/rewards", _Marketing_CreateReward0_HTTP_Handler(srv))
	r.GET("/v1/rewards/{reward_id}", _Marketing_GetReward0_HTTP_Handler(srv))
	r.GET("/v1/rewards", _Marketing_ListRewards0_HTTP_Handler(srv))
	r.PUT("/v1/rewards/{reward_id}", _Marketing_UpdateReward0_HTTP_Handler(srv))
	r.DELETE("/v1/rewards/{reward_id}", _Marketing_DeleteReward0_HTTP_Handler(srv))
	r.POST("/v1/tasks", _Marketing_CreateTask0_HTTP_Handler(srv))
	r.GET("/v1/tasks/{task_id}", _Marketing_GetTask0_HTTP_Handler(srv))
	r.GET("/v1/tasks", _Marketing_ListTasks0_HTTP_Handler(srv))
	r.PUT("/v1/tasks/{task_id}", _Marketing_UpdateTask0_HTTP_Handler(srv))
	r.DELETE("/v1/tasks/{task_id}", _Marketing_DeleteTask0_HTTP_Handler(srv))
	r.GET("/v1/campaigns/{campaign_id}/tasks", _Marketing_ListTasksByCampaign0_HTTP_Handler(srv))
	r.POST("/v1/audiences", _Marketing_CreateAudience0_HTTP_Handler(srv))
	r.GET("/v1/audiences/{audience_id}", _Marketing_GetAudience0_HTTP_Handler(srv))
	r.GET("/v1/audiences", _Marketing_ListAudiences0_HTTP_Handler(srv))
	r.PUT("/v1/audiences/{audience_id}", _Marketing_UpdateAudience0_HTTP_Handler(srv))
	r.DELETE("/v1/audiences/{audience_id}", _Marketing_DeleteAudience0_HTTP_Handler(srv))
	r.GET("/v1/reward-grants", _Marketing_ListRewardGrants0_HTTP_Handler(srv))
	r.GET("/v1/reward-grants/{grant_id}", _Marketing_GetRewardGrant0_HTTP_Handler(srv))
	r.PUT("/v1/reward-grants/{grant_id}/status", _Marketing_UpdateRewardGrantStatus0_HTTP_Handler(srv))
	r.POST("/v1/tasks/trigger", _Marketing_TriggerTaskEvent0_HTTP_Handler(srv))
	r.POST("/v1/inventory/reserve", _Marketing_ReserveInventory0_HTTP_Handler(srv))
	r.POST("/v1/inventory/{reservation_id}/confirm", _Marketing_ConfirmInventory0_HTTP_Handler(srv))
	r.POST("/v1/inventory/{reservation_id}/cancel", _Marketing_CancelInventory0_HTTP_Handler(srv))
	r.GET("/v1/inventory/reservations", _Marketing_ListInventoryReservations0_HTTP_Handler(srv))
	r.GET("/v1/task-completion-logs", _Marketing_ListTaskCompletionLogs0_HTTP_Handler(srv))
	r.GET("/v1/tasks/{task_id}/completion-stats", _Marketing_GetTaskCompletionStats0_HTTP_Handler(srv))
	r.POST("/v1/campaigns/{campaign_id}/tasks", _Marketing_AddTaskToCampaign0_HTTP_Handler(srv))
	r.DELETE("/v1/campaigns/{campaign_id}/tasks/{task_id}", _Marketing_RemoveTaskFromCampaign0_HTTP_Handler(srv))
	r.GET("/v1/campaigns/{campaign_id}/tasks", _Marketing_ListCampaignTasks0_HTTP_Handler(srv))
}

func _Marketing_CreateCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCampaignRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingCreateCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCampaign(ctx, req.(*CreateCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCampaignRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCampaign(ctx, req.(*GetCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListCampaigns0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCampaignsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListCampaigns)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCampaigns(ctx, req.(*ListCampaignsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCampaignsReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_UpdateCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCampaignRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingUpdateCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCampaign(ctx, req.(*UpdateCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_DeleteCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCampaignRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingDeleteCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCampaign(ctx, req.(*DeleteCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GenerateRedeemCodes0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateRedeemCodesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGenerateRedeemCodes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateRedeemCodes(ctx, req.(*GenerateRedeemCodesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateRedeemCodesReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_RedeemCode0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RedeemCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingRedeemCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RedeemCode(ctx, req.(*RedeemCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RedeemCodeReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_AssignRedeemCode0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignRedeemCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingAssignRedeemCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignRedeemCode(ctx, req.(*AssignRedeemCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AssignRedeemCodeReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListRedeemCodes0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRedeemCodesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListRedeemCodes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRedeemCodes(ctx, req.(*ListRedeemCodesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRedeemCodesReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetRedeemCode0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRedeemCodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetRedeemCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRedeemCode(ctx, req.(*GetRedeemCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRedeemCodeReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_CreateReward0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRewardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingCreateReward)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateReward(ctx, req.(*CreateRewardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateRewardReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetReward0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRewardRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetReward)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetReward(ctx, req.(*GetRewardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRewardReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListRewards0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRewardsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListRewards)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRewards(ctx, req.(*ListRewardsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRewardsReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_UpdateReward0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRewardRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingUpdateReward)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateReward(ctx, req.(*UpdateRewardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateRewardReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_DeleteReward0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRewardRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingDeleteReward)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteReward(ctx, req.(*DeleteRewardRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteRewardReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_CreateTask0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingCreateTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateTask(ctx, req.(*CreateTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateTaskReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetTask0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTask(ctx, req.(*GetTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTaskReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListTasks0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTasks(ctx, req.(*ListTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTasksReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_UpdateTask0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateTaskRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingUpdateTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateTask(ctx, req.(*UpdateTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateTaskReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_DeleteTask0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteTaskRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingDeleteTask)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteTask(ctx, req.(*DeleteTaskRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteTaskReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListTasksByCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTasksByCampaignRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListTasksByCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTasksByCampaign(ctx, req.(*ListTasksByCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTasksByCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_CreateAudience0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateAudienceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingCreateAudience)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateAudience(ctx, req.(*CreateAudienceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateAudienceReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetAudience0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetAudienceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetAudience)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAudience(ctx, req.(*GetAudienceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetAudienceReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListAudiences0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListAudiencesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListAudiences)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListAudiences(ctx, req.(*ListAudiencesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListAudiencesReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_UpdateAudience0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateAudienceRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingUpdateAudience)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateAudience(ctx, req.(*UpdateAudienceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateAudienceReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_DeleteAudience0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteAudienceRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingDeleteAudience)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteAudience(ctx, req.(*DeleteAudienceRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteAudienceReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListRewardGrants0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRewardGrantsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListRewardGrants)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRewardGrants(ctx, req.(*ListRewardGrantsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRewardGrantsReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetRewardGrant0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRewardGrantRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetRewardGrant)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRewardGrant(ctx, req.(*GetRewardGrantRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRewardGrantReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_UpdateRewardGrantStatus0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRewardGrantStatusRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingUpdateRewardGrantStatus)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateRewardGrantStatus(ctx, req.(*UpdateRewardGrantStatusRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateRewardGrantStatusReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_TriggerTaskEvent0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TriggerTaskEventRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingTriggerTaskEvent)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.TriggerTaskEvent(ctx, req.(*TriggerTaskEventRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TriggerTaskEventReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ReserveInventory0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ReserveInventoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingReserveInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ReserveInventory(ctx, req.(*ReserveInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ReserveInventoryReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ConfirmInventory0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ConfirmInventoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingConfirmInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ConfirmInventory(ctx, req.(*ConfirmInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ConfirmInventoryReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_CancelInventory0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CancelInventoryRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingCancelInventory)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CancelInventory(ctx, req.(*CancelInventoryRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CancelInventoryReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListInventoryReservations0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListInventoryReservationsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListInventoryReservations)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListInventoryReservations(ctx, req.(*ListInventoryReservationsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListInventoryReservationsReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListTaskCompletionLogs0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListTaskCompletionLogsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListTaskCompletionLogs)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListTaskCompletionLogs(ctx, req.(*ListTaskCompletionLogsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListTaskCompletionLogsReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetTaskCompletionStats0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetTaskCompletionStatsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetTaskCompletionStats)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTaskCompletionStats(ctx, req.(*GetTaskCompletionStatsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetTaskCompletionStatsReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_AddTaskToCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AddTaskToCampaignRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingAddTaskToCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AddTaskToCampaign(ctx, req.(*AddTaskToCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AddTaskToCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_RemoveTaskFromCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RemoveTaskFromCampaignRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingRemoveTaskFromCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RemoveTaskFromCampaign(ctx, req.(*RemoveTaskFromCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RemoveTaskFromCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListCampaignTasks0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCampaignTasksRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListCampaignTasks)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCampaignTasks(ctx, req.(*ListCampaignTasksRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCampaignTasksReply)
		return ctx.Result(200, reply)
	}
}

type MarketingHTTPClient interface {
	// AddTaskToCampaign ========== Campaign Task Management API ==========
	// AddTaskToCampaign 将任务添加到活动
	AddTaskToCampaign(ctx context.Context, req *AddTaskToCampaignRequest, opts ...http.CallOption) (rsp *AddTaskToCampaignReply, err error)
	// AssignRedeemCode AssignRedeemCode 分配兑换码
	AssignRedeemCode(ctx context.Context, req *AssignRedeemCodeRequest, opts ...http.CallOption) (rsp *AssignRedeemCodeReply, err error)
	// CancelInventory CancelInventory 取消库存
	CancelInventory(ctx context.Context, req *CancelInventoryRequest, opts ...http.CallOption) (rsp *CancelInventoryReply, err error)
	// ConfirmInventory ConfirmInventory 确认库存
	ConfirmInventory(ctx context.Context, req *ConfirmInventoryRequest, opts ...http.CallOption) (rsp *ConfirmInventoryReply, err error)
	// CreateAudience ========== Audience API ==========
	// CreateAudience 创建受众
	CreateAudience(ctx context.Context, req *CreateAudienceRequest, opts ...http.CallOption) (rsp *CreateAudienceReply, err error)
	// CreateCampaign CreateCampaign 创建营销活动
	CreateCampaign(ctx context.Context, req *CreateCampaignRequest, opts ...http.CallOption) (rsp *CreateCampaignReply, err error)
	// CreateReward ========== Reward API ==========
	// CreateReward 创建奖励
	CreateReward(ctx context.Context, req *CreateRewardRequest, opts ...http.CallOption) (rsp *CreateRewardReply, err error)
	// CreateTask ========== Task API ==========
	// CreateTask 创建任务
	CreateTask(ctx context.Context, req *CreateTaskRequest, opts ...http.CallOption) (rsp *CreateTaskReply, err error)
	// DeleteAudience DeleteAudience 删除受众
	DeleteAudience(ctx context.Context, req *DeleteAudienceRequest, opts ...http.CallOption) (rsp *DeleteAudienceReply, err error)
	// DeleteCampaign DeleteCampaign 删除营销活动
	DeleteCampaign(ctx context.Context, req *DeleteCampaignRequest, opts ...http.CallOption) (rsp *DeleteCampaignReply, err error)
	// DeleteReward DeleteReward 删除奖励
	DeleteReward(ctx context.Context, req *DeleteRewardRequest, opts ...http.CallOption) (rsp *DeleteRewardReply, err error)
	// DeleteTask DeleteTask 删除任务
	DeleteTask(ctx context.Context, req *DeleteTaskRequest, opts ...http.CallOption) (rsp *DeleteTaskReply, err error)
	// GenerateRedeemCodes GenerateRedeemCodes 生成兑换码
	GenerateRedeemCodes(ctx context.Context, req *GenerateRedeemCodesRequest, opts ...http.CallOption) (rsp *GenerateRedeemCodesReply, err error)
	// GetAudience GetAudience 获取受众
	GetAudience(ctx context.Context, req *GetAudienceRequest, opts ...http.CallOption) (rsp *GetAudienceReply, err error)
	// GetCampaign GetCampaign 获取营销活动
	GetCampaign(ctx context.Context, req *GetCampaignRequest, opts ...http.CallOption) (rsp *GetCampaignReply, err error)
	// GetRedeemCode GetRedeemCode 获取兑换码
	GetRedeemCode(ctx context.Context, req *GetRedeemCodeRequest, opts ...http.CallOption) (rsp *GetRedeemCodeReply, err error)
	// GetReward GetReward 获取奖励
	GetReward(ctx context.Context, req *GetRewardRequest, opts ...http.CallOption) (rsp *GetRewardReply, err error)
	// GetRewardGrant GetRewardGrant 获取奖励发放记录
	GetRewardGrant(ctx context.Context, req *GetRewardGrantRequest, opts ...http.CallOption) (rsp *GetRewardGrantReply, err error)
	// GetTask GetTask 获取任务
	GetTask(ctx context.Context, req *GetTaskRequest, opts ...http.CallOption) (rsp *GetTaskReply, err error)
	// GetTaskCompletionStats GetTaskCompletionStats 获取任务完成统计
	GetTaskCompletionStats(ctx context.Context, req *GetTaskCompletionStatsRequest, opts ...http.CallOption) (rsp *GetTaskCompletionStatsReply, err error)
	// ListAudiences ListAudiences 列出受众
	ListAudiences(ctx context.Context, req *ListAudiencesRequest, opts ...http.CallOption) (rsp *ListAudiencesReply, err error)
	// ListCampaignTasks ListCampaignTasks 列出活动的所有任务
	ListCampaignTasks(ctx context.Context, req *ListCampaignTasksRequest, opts ...http.CallOption) (rsp *ListCampaignTasksReply, err error)
	// ListCampaigns ListCampaigns 列出营销活动
	ListCampaigns(ctx context.Context, req *ListCampaignsRequest, opts ...http.CallOption) (rsp *ListCampaignsReply, err error)
	// ListInventoryReservations ListInventoryReservations 列出库存预占记录
	ListInventoryReservations(ctx context.Context, req *ListInventoryReservationsRequest, opts ...http.CallOption) (rsp *ListInventoryReservationsReply, err error)
	// ListRedeemCodes ListRedeemCodes 列出兑换码
	ListRedeemCodes(ctx context.Context, req *ListRedeemCodesRequest, opts ...http.CallOption) (rsp *ListRedeemCodesReply, err error)
	// ListRewardGrants ========== RewardGrant API ==========
	// ListRewardGrants 列出奖励发放记录
	ListRewardGrants(ctx context.Context, req *ListRewardGrantsRequest, opts ...http.CallOption) (rsp *ListRewardGrantsReply, err error)
	// ListRewards ListRewards 列出奖励
	ListRewards(ctx context.Context, req *ListRewardsRequest, opts ...http.CallOption) (rsp *ListRewardsReply, err error)
	// ListTaskCompletionLogs ========== Task Completion Log API ==========
	// ListTaskCompletionLogs 列出任务完成日志
	ListTaskCompletionLogs(ctx context.Context, req *ListTaskCompletionLogsRequest, opts ...http.CallOption) (rsp *ListTaskCompletionLogsReply, err error)
	// ListTasks ListTasks 列出任务
	ListTasks(ctx context.Context, req *ListTasksRequest, opts ...http.CallOption) (rsp *ListTasksReply, err error)
	// ListTasksByCampaign ListTasksByCampaign 根据活动列出任务
	ListTasksByCampaign(ctx context.Context, req *ListTasksByCampaignRequest, opts ...http.CallOption) (rsp *ListTasksByCampaignReply, err error)
	// RedeemCode RedeemCode 兑换码核销
	RedeemCode(ctx context.Context, req *RedeemCodeRequest, opts ...http.CallOption) (rsp *RedeemCodeReply, err error)
	// RemoveTaskFromCampaign RemoveTaskFromCampaign 从活动中移除任务
	RemoveTaskFromCampaign(ctx context.Context, req *RemoveTaskFromCampaignRequest, opts ...http.CallOption) (rsp *RemoveTaskFromCampaignReply, err error)
	// ReserveInventory ========== Inventory Management API ==========
	// ReserveInventory 预占库存
	ReserveInventory(ctx context.Context, req *ReserveInventoryRequest, opts ...http.CallOption) (rsp *ReserveInventoryReply, err error)
	// TriggerTaskEvent ========== Task Event API ==========
	// TriggerTaskEvent 触发任务事件
	TriggerTaskEvent(ctx context.Context, req *TriggerTaskEventRequest, opts ...http.CallOption) (rsp *TriggerTaskEventReply, err error)
	// UpdateAudience UpdateAudience 更新受众
	UpdateAudience(ctx context.Context, req *UpdateAudienceRequest, opts ...http.CallOption) (rsp *UpdateAudienceReply, err error)
	// UpdateCampaign UpdateCampaign 更新营销活动
	UpdateCampaign(ctx context.Context, req *UpdateCampaignRequest, opts ...http.CallOption) (rsp *UpdateCampaignReply, err error)
	// UpdateReward UpdateReward 更新奖励
	UpdateReward(ctx context.Context, req *UpdateRewardRequest, opts ...http.CallOption) (rsp *UpdateRewardReply, err error)
	// UpdateRewardGrantStatus UpdateRewardGrantStatus 更新发放状态
	UpdateRewardGrantStatus(ctx context.Context, req *UpdateRewardGrantStatusRequest, opts ...http.CallOption) (rsp *UpdateRewardGrantStatusReply, err error)
	// UpdateTask UpdateTask 更新任务
	UpdateTask(ctx context.Context, req *UpdateTaskRequest, opts ...http.CallOption) (rsp *UpdateTaskReply, err error)
}

type MarketingHTTPClientImpl struct {
	cc *http.Client
}

func NewMarketingHTTPClient(client *http.Client) MarketingHTTPClient {
	return &MarketingHTTPClientImpl{client}
}

// AddTaskToCampaign ========== Campaign Task Management API ==========
// AddTaskToCampaign 将任务添加到活动
func (c *MarketingHTTPClientImpl) AddTaskToCampaign(ctx context.Context, in *AddTaskToCampaignRequest, opts ...http.CallOption) (*AddTaskToCampaignReply, error) {
	var out AddTaskToCampaignReply
	pattern := "/v1/campaigns/{campaign_id}/tasks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingAddTaskToCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// AssignRedeemCode AssignRedeemCode 分配兑换码
func (c *MarketingHTTPClientImpl) AssignRedeemCode(ctx context.Context, in *AssignRedeemCodeRequest, opts ...http.CallOption) (*AssignRedeemCodeReply, error) {
	var out AssignRedeemCodeReply
	pattern := "/v1/redeem-codes/{code}/assign"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingAssignRedeemCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CancelInventory CancelInventory 取消库存
func (c *MarketingHTTPClientImpl) CancelInventory(ctx context.Context, in *CancelInventoryRequest, opts ...http.CallOption) (*CancelInventoryReply, error) {
	var out CancelInventoryReply
	pattern := "/v1/inventory/{reservation_id}/cancel"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingCancelInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ConfirmInventory ConfirmInventory 确认库存
func (c *MarketingHTTPClientImpl) ConfirmInventory(ctx context.Context, in *ConfirmInventoryRequest, opts ...http.CallOption) (*ConfirmInventoryReply, error) {
	var out ConfirmInventoryReply
	pattern := "/v1/inventory/{reservation_id}/confirm"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingConfirmInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateAudience ========== Audience API ==========
// CreateAudience 创建受众
func (c *MarketingHTTPClientImpl) CreateAudience(ctx context.Context, in *CreateAudienceRequest, opts ...http.CallOption) (*CreateAudienceReply, error) {
	var out CreateAudienceReply
	pattern := "/v1/audiences"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingCreateAudience))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateCampaign CreateCampaign 创建营销活动
func (c *MarketingHTTPClientImpl) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...http.CallOption) (*CreateCampaignReply, error) {
	var out CreateCampaignReply
	pattern := "/v1/campaigns"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingCreateCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateReward ========== Reward API ==========
// CreateReward 创建奖励
func (c *MarketingHTTPClientImpl) CreateReward(ctx context.Context, in *CreateRewardRequest, opts ...http.CallOption) (*CreateRewardReply, error) {
	var out CreateRewardReply
	pattern := "/v1/rewards"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingCreateReward))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// CreateTask ========== Task API ==========
// CreateTask 创建任务
func (c *MarketingHTTPClientImpl) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...http.CallOption) (*CreateTaskReply, error) {
	var out CreateTaskReply
	pattern := "/v1/tasks"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingCreateTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteAudience DeleteAudience 删除受众
func (c *MarketingHTTPClientImpl) DeleteAudience(ctx context.Context, in *DeleteAudienceRequest, opts ...http.CallOption) (*DeleteAudienceReply, error) {
	var out DeleteAudienceReply
	pattern := "/v1/audiences/{audience_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingDeleteAudience))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteCampaign DeleteCampaign 删除营销活动
func (c *MarketingHTTPClientImpl) DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...http.CallOption) (*DeleteCampaignReply, error) {
	var out DeleteCampaignReply
	pattern := "/v1/campaigns/{campaign_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingDeleteCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteReward DeleteReward 删除奖励
func (c *MarketingHTTPClientImpl) DeleteReward(ctx context.Context, in *DeleteRewardRequest, opts ...http.CallOption) (*DeleteRewardReply, error) {
	var out DeleteRewardReply
	pattern := "/v1/rewards/{reward_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingDeleteReward))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// DeleteTask DeleteTask 删除任务
func (c *MarketingHTTPClientImpl) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...http.CallOption) (*DeleteTaskReply, error) {
	var out DeleteTaskReply
	pattern := "/v1/tasks/{task_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingDeleteTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GenerateRedeemCodes GenerateRedeemCodes 生成兑换码
func (c *MarketingHTTPClientImpl) GenerateRedeemCodes(ctx context.Context, in *GenerateRedeemCodesRequest, opts ...http.CallOption) (*GenerateRedeemCodesReply, error) {
	var out GenerateRedeemCodesReply
	pattern := "/v1/campaigns/{campaign_id}/redeem-codes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingGenerateRedeemCodes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetAudience GetAudience 获取受众
func (c *MarketingHTTPClientImpl) GetAudience(ctx context.Context, in *GetAudienceRequest, opts ...http.CallOption) (*GetAudienceReply, error) {
	var out GetAudienceReply
	pattern := "/v1/audiences/{audience_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetAudience))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetCampaign GetCampaign 获取营销活动
func (c *MarketingHTTPClientImpl) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...http.CallOption) (*GetCampaignReply, error) {
	var out GetCampaignReply
	pattern := "/v1/campaigns/{campaign_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRedeemCode GetRedeemCode 获取兑换码
func (c *MarketingHTTPClientImpl) GetRedeemCode(ctx context.Context, in *GetRedeemCodeRequest, opts ...http.CallOption) (*GetRedeemCodeReply, error) {
	var out GetRedeemCodeReply
	pattern := "/v1/redeem-codes/{code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetRedeemCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetReward GetReward 获取奖励
func (c *MarketingHTTPClientImpl) GetReward(ctx context.Context, in *GetRewardRequest, opts ...http.CallOption) (*GetRewardReply, error) {
	var out GetRewardReply
	pattern := "/v1/rewards/{reward_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetReward))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetRewardGrant GetRewardGrant 获取奖励发放记录
func (c *MarketingHTTPClientImpl) GetRewardGrant(ctx context.Context, in *GetRewardGrantRequest, opts ...http.CallOption) (*GetRewardGrantReply, error) {
	var out GetRewardGrantReply
	pattern := "/v1/reward-grants/{grant_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetRewardGrant))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTask GetTask 获取任务
func (c *MarketingHTTPClientImpl) GetTask(ctx context.Context, in *GetTaskRequest, opts ...http.CallOption) (*GetTaskReply, error) {
	var out GetTaskReply
	pattern := "/v1/tasks/{task_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// GetTaskCompletionStats GetTaskCompletionStats 获取任务完成统计
func (c *MarketingHTTPClientImpl) GetTaskCompletionStats(ctx context.Context, in *GetTaskCompletionStatsRequest, opts ...http.CallOption) (*GetTaskCompletionStatsReply, error) {
	var out GetTaskCompletionStatsReply
	pattern := "/v1/tasks/{task_id}/completion-stats"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetTaskCompletionStats))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListAudiences ListAudiences 列出受众
func (c *MarketingHTTPClientImpl) ListAudiences(ctx context.Context, in *ListAudiencesRequest, opts ...http.CallOption) (*ListAudiencesReply, error) {
	var out ListAudiencesReply
	pattern := "/v1/audiences"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListAudiences))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCampaignTasks ListCampaignTasks 列出活动的所有任务
func (c *MarketingHTTPClientImpl) ListCampaignTasks(ctx context.Context, in *ListCampaignTasksRequest, opts ...http.CallOption) (*ListCampaignTasksReply, error) {
	var out ListCampaignTasksReply
	pattern := "/v1/campaigns/{campaign_id}/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListCampaignTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListCampaigns ListCampaigns 列出营销活动
func (c *MarketingHTTPClientImpl) ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...http.CallOption) (*ListCampaignsReply, error) {
	var out ListCampaignsReply
	pattern := "/v1/campaigns"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListCampaigns))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListInventoryReservations ListInventoryReservations 列出库存预占记录
func (c *MarketingHTTPClientImpl) ListInventoryReservations(ctx context.Context, in *ListInventoryReservationsRequest, opts ...http.CallOption) (*ListInventoryReservationsReply, error) {
	var out ListInventoryReservationsReply
	pattern := "/v1/inventory/reservations"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListInventoryReservations))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRedeemCodes ListRedeemCodes 列出兑换码
func (c *MarketingHTTPClientImpl) ListRedeemCodes(ctx context.Context, in *ListRedeemCodesRequest, opts ...http.CallOption) (*ListRedeemCodesReply, error) {
	var out ListRedeemCodesReply
	pattern := "/v1/redeem-codes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListRedeemCodes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRewardGrants ========== RewardGrant API ==========
// ListRewardGrants 列出奖励发放记录
func (c *MarketingHTTPClientImpl) ListRewardGrants(ctx context.Context, in *ListRewardGrantsRequest, opts ...http.CallOption) (*ListRewardGrantsReply, error) {
	var out ListRewardGrantsReply
	pattern := "/v1/reward-grants"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListRewardGrants))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListRewards ListRewards 列出奖励
func (c *MarketingHTTPClientImpl) ListRewards(ctx context.Context, in *ListRewardsRequest, opts ...http.CallOption) (*ListRewardsReply, error) {
	var out ListRewardsReply
	pattern := "/v1/rewards"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListRewards))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTaskCompletionLogs ========== Task Completion Log API ==========
// ListTaskCompletionLogs 列出任务完成日志
func (c *MarketingHTTPClientImpl) ListTaskCompletionLogs(ctx context.Context, in *ListTaskCompletionLogsRequest, opts ...http.CallOption) (*ListTaskCompletionLogsReply, error) {
	var out ListTaskCompletionLogsReply
	pattern := "/v1/task-completion-logs"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListTaskCompletionLogs))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTasks ListTasks 列出任务
func (c *MarketingHTTPClientImpl) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...http.CallOption) (*ListTasksReply, error) {
	var out ListTasksReply
	pattern := "/v1/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListTasks))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ListTasksByCampaign ListTasksByCampaign 根据活动列出任务
func (c *MarketingHTTPClientImpl) ListTasksByCampaign(ctx context.Context, in *ListTasksByCampaignRequest, opts ...http.CallOption) (*ListTasksByCampaignReply, error) {
	var out ListTasksByCampaignReply
	pattern := "/v1/campaigns/{campaign_id}/tasks"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListTasksByCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RedeemCode RedeemCode 兑换码核销
func (c *MarketingHTTPClientImpl) RedeemCode(ctx context.Context, in *RedeemCodeRequest, opts ...http.CallOption) (*RedeemCodeReply, error) {
	var out RedeemCodeReply
	pattern := "/v1/redeem"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingRedeemCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// RemoveTaskFromCampaign RemoveTaskFromCampaign 从活动中移除任务
func (c *MarketingHTTPClientImpl) RemoveTaskFromCampaign(ctx context.Context, in *RemoveTaskFromCampaignRequest, opts ...http.CallOption) (*RemoveTaskFromCampaignReply, error) {
	var out RemoveTaskFromCampaignReply
	pattern := "/v1/campaigns/{campaign_id}/tasks/{task_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingRemoveTaskFromCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// ReserveInventory ========== Inventory Management API ==========
// ReserveInventory 预占库存
func (c *MarketingHTTPClientImpl) ReserveInventory(ctx context.Context, in *ReserveInventoryRequest, opts ...http.CallOption) (*ReserveInventoryReply, error) {
	var out ReserveInventoryReply
	pattern := "/v1/inventory/reserve"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingReserveInventory))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// TriggerTaskEvent ========== Task Event API ==========
// TriggerTaskEvent 触发任务事件
func (c *MarketingHTTPClientImpl) TriggerTaskEvent(ctx context.Context, in *TriggerTaskEventRequest, opts ...http.CallOption) (*TriggerTaskEventReply, error) {
	var out TriggerTaskEventReply
	pattern := "/v1/tasks/trigger"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingTriggerTaskEvent))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateAudience UpdateAudience 更新受众
func (c *MarketingHTTPClientImpl) UpdateAudience(ctx context.Context, in *UpdateAudienceRequest, opts ...http.CallOption) (*UpdateAudienceReply, error) {
	var out UpdateAudienceReply
	pattern := "/v1/audiences/{audience_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingUpdateAudience))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateCampaign UpdateCampaign 更新营销活动
func (c *MarketingHTTPClientImpl) UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...http.CallOption) (*UpdateCampaignReply, error) {
	var out UpdateCampaignReply
	pattern := "/v1/campaigns/{campaign_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingUpdateCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateReward UpdateReward 更新奖励
func (c *MarketingHTTPClientImpl) UpdateReward(ctx context.Context, in *UpdateRewardRequest, opts ...http.CallOption) (*UpdateRewardReply, error) {
	var out UpdateRewardReply
	pattern := "/v1/rewards/{reward_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingUpdateReward))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateRewardGrantStatus UpdateRewardGrantStatus 更新发放状态
func (c *MarketingHTTPClientImpl) UpdateRewardGrantStatus(ctx context.Context, in *UpdateRewardGrantStatusRequest, opts ...http.CallOption) (*UpdateRewardGrantStatusReply, error) {
	var out UpdateRewardGrantStatusReply
	pattern := "/v1/reward-grants/{grant_id}/status"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingUpdateRewardGrantStatus))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

// UpdateTask UpdateTask 更新任务
func (c *MarketingHTTPClientImpl) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...http.CallOption) (*UpdateTaskReply, error) {
	var out UpdateTaskReply
	pattern := "/v1/tasks/{task_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingUpdateTask))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
