// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: marketing.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Marketing_CreateCampaign_FullMethodName            = "/platform.marketing_service.v1.Marketing/CreateCampaign"
	Marketing_GetCampaign_FullMethodName               = "/platform.marketing_service.v1.Marketing/GetCampaign"
	Marketing_ListCampaigns_FullMethodName             = "/platform.marketing_service.v1.Marketing/ListCampaigns"
	Marketing_UpdateCampaign_FullMethodName            = "/platform.marketing_service.v1.Marketing/UpdateCampaign"
	Marketing_DeleteCampaign_FullMethodName            = "/platform.marketing_service.v1.Marketing/DeleteCampaign"
	Marketing_GenerateRedeemCodes_FullMethodName       = "/platform.marketing_service.v1.Marketing/GenerateRedeemCodes"
	Marketing_RedeemCode_FullMethodName                = "/platform.marketing_service.v1.Marketing/RedeemCode"
	Marketing_AssignRedeemCode_FullMethodName          = "/platform.marketing_service.v1.Marketing/AssignRedeemCode"
	Marketing_ListRedeemCodes_FullMethodName           = "/platform.marketing_service.v1.Marketing/ListRedeemCodes"
	Marketing_GetRedeemCode_FullMethodName             = "/platform.marketing_service.v1.Marketing/GetRedeemCode"
	Marketing_CreateReward_FullMethodName              = "/platform.marketing_service.v1.Marketing/CreateReward"
	Marketing_GetReward_FullMethodName                 = "/platform.marketing_service.v1.Marketing/GetReward"
	Marketing_ListRewards_FullMethodName               = "/platform.marketing_service.v1.Marketing/ListRewards"
	Marketing_UpdateReward_FullMethodName              = "/platform.marketing_service.v1.Marketing/UpdateReward"
	Marketing_DeleteReward_FullMethodName              = "/platform.marketing_service.v1.Marketing/DeleteReward"
	Marketing_CreateTask_FullMethodName                = "/platform.marketing_service.v1.Marketing/CreateTask"
	Marketing_GetTask_FullMethodName                   = "/platform.marketing_service.v1.Marketing/GetTask"
	Marketing_ListTasks_FullMethodName                 = "/platform.marketing_service.v1.Marketing/ListTasks"
	Marketing_UpdateTask_FullMethodName                = "/platform.marketing_service.v1.Marketing/UpdateTask"
	Marketing_DeleteTask_FullMethodName                = "/platform.marketing_service.v1.Marketing/DeleteTask"
	Marketing_ListTasksByCampaign_FullMethodName       = "/platform.marketing_service.v1.Marketing/ListTasksByCampaign"
	Marketing_CreateAudience_FullMethodName            = "/platform.marketing_service.v1.Marketing/CreateAudience"
	Marketing_GetAudience_FullMethodName               = "/platform.marketing_service.v1.Marketing/GetAudience"
	Marketing_ListAudiences_FullMethodName             = "/platform.marketing_service.v1.Marketing/ListAudiences"
	Marketing_UpdateAudience_FullMethodName            = "/platform.marketing_service.v1.Marketing/UpdateAudience"
	Marketing_DeleteAudience_FullMethodName            = "/platform.marketing_service.v1.Marketing/DeleteAudience"
	Marketing_ListRewardGrants_FullMethodName          = "/platform.marketing_service.v1.Marketing/ListRewardGrants"
	Marketing_GetRewardGrant_FullMethodName            = "/platform.marketing_service.v1.Marketing/GetRewardGrant"
	Marketing_UpdateRewardGrantStatus_FullMethodName   = "/platform.marketing_service.v1.Marketing/UpdateRewardGrantStatus"
	Marketing_TriggerTaskEvent_FullMethodName          = "/platform.marketing_service.v1.Marketing/TriggerTaskEvent"
	Marketing_ReserveInventory_FullMethodName          = "/platform.marketing_service.v1.Marketing/ReserveInventory"
	Marketing_ConfirmInventory_FullMethodName          = "/platform.marketing_service.v1.Marketing/ConfirmInventory"
	Marketing_CancelInventory_FullMethodName           = "/platform.marketing_service.v1.Marketing/CancelInventory"
	Marketing_ListInventoryReservations_FullMethodName = "/platform.marketing_service.v1.Marketing/ListInventoryReservations"
	Marketing_ListTaskCompletionLogs_FullMethodName    = "/platform.marketing_service.v1.Marketing/ListTaskCompletionLogs"
	Marketing_GetTaskCompletionStats_FullMethodName    = "/platform.marketing_service.v1.Marketing/GetTaskCompletionStats"
	Marketing_AddTaskToCampaign_FullMethodName         = "/platform.marketing_service.v1.Marketing/AddTaskToCampaign"
	Marketing_RemoveTaskFromCampaign_FullMethodName    = "/platform.marketing_service.v1.Marketing/RemoveTaskFromCampaign"
	Marketing_ListCampaignTasks_FullMethodName         = "/platform.marketing_service.v1.Marketing/ListCampaignTasks"
)

// MarketingClient is the client API for Marketing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketingService 营销服务API
type MarketingClient interface {
	// CreateCampaign 创建营销活动
	CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignReply, error)
	// GetCampaign 获取营销活动
	GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*GetCampaignReply, error)
	// ListCampaigns 列出营销活动
	ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsReply, error)
	// UpdateCampaign 更新营销活动
	UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...grpc.CallOption) (*UpdateCampaignReply, error)
	// DeleteCampaign 删除营销活动
	DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteCampaignReply, error)
	// GenerateRedeemCodes 生成兑换码
	GenerateRedeemCodes(ctx context.Context, in *GenerateRedeemCodesRequest, opts ...grpc.CallOption) (*GenerateRedeemCodesReply, error)
	// RedeemCode 兑换码核销
	RedeemCode(ctx context.Context, in *RedeemCodeRequest, opts ...grpc.CallOption) (*RedeemCodeReply, error)
	// AssignRedeemCode 分配兑换码
	AssignRedeemCode(ctx context.Context, in *AssignRedeemCodeRequest, opts ...grpc.CallOption) (*AssignRedeemCodeReply, error)
	// ListRedeemCodes 列出兑换码
	ListRedeemCodes(ctx context.Context, in *ListRedeemCodesRequest, opts ...grpc.CallOption) (*ListRedeemCodesReply, error)
	// GetRedeemCode 获取兑换码
	GetRedeemCode(ctx context.Context, in *GetRedeemCodeRequest, opts ...grpc.CallOption) (*GetRedeemCodeReply, error)
	// ========== Reward API ==========
	// CreateReward 创建奖励
	CreateReward(ctx context.Context, in *CreateRewardRequest, opts ...grpc.CallOption) (*CreateRewardReply, error)
	// GetReward 获取奖励
	GetReward(ctx context.Context, in *GetRewardRequest, opts ...grpc.CallOption) (*GetRewardReply, error)
	// ListRewards 列出奖励
	ListRewards(ctx context.Context, in *ListRewardsRequest, opts ...grpc.CallOption) (*ListRewardsReply, error)
	// UpdateReward 更新奖励
	UpdateReward(ctx context.Context, in *UpdateRewardRequest, opts ...grpc.CallOption) (*UpdateRewardReply, error)
	// DeleteReward 删除奖励
	DeleteReward(ctx context.Context, in *DeleteRewardRequest, opts ...grpc.CallOption) (*DeleteRewardReply, error)
	// ========== Task API ==========
	// CreateTask 创建任务
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskReply, error)
	// GetTask 获取任务
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskReply, error)
	// ListTasks 列出任务
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksReply, error)
	// UpdateTask 更新任务
	UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskReply, error)
	// DeleteTask 删除任务
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskReply, error)
	// ListTasksByCampaign 根据活动列出任务
	ListTasksByCampaign(ctx context.Context, in *ListTasksByCampaignRequest, opts ...grpc.CallOption) (*ListTasksByCampaignReply, error)
	// ========== Audience API ==========
	// CreateAudience 创建受众
	CreateAudience(ctx context.Context, in *CreateAudienceRequest, opts ...grpc.CallOption) (*CreateAudienceReply, error)
	// GetAudience 获取受众
	GetAudience(ctx context.Context, in *GetAudienceRequest, opts ...grpc.CallOption) (*GetAudienceReply, error)
	// ListAudiences 列出受众
	ListAudiences(ctx context.Context, in *ListAudiencesRequest, opts ...grpc.CallOption) (*ListAudiencesReply, error)
	// UpdateAudience 更新受众
	UpdateAudience(ctx context.Context, in *UpdateAudienceRequest, opts ...grpc.CallOption) (*UpdateAudienceReply, error)
	// DeleteAudience 删除受众
	DeleteAudience(ctx context.Context, in *DeleteAudienceRequest, opts ...grpc.CallOption) (*DeleteAudienceReply, error)
	// ========== RewardGrant API ==========
	// ListRewardGrants 列出奖励发放记录
	ListRewardGrants(ctx context.Context, in *ListRewardGrantsRequest, opts ...grpc.CallOption) (*ListRewardGrantsReply, error)
	// GetRewardGrant 获取奖励发放记录
	GetRewardGrant(ctx context.Context, in *GetRewardGrantRequest, opts ...grpc.CallOption) (*GetRewardGrantReply, error)
	// UpdateRewardGrantStatus 更新发放状态
	UpdateRewardGrantStatus(ctx context.Context, in *UpdateRewardGrantStatusRequest, opts ...grpc.CallOption) (*UpdateRewardGrantStatusReply, error)
	// ========== Task Event API ==========
	// TriggerTaskEvent 触发任务事件
	TriggerTaskEvent(ctx context.Context, in *TriggerTaskEventRequest, opts ...grpc.CallOption) (*TriggerTaskEventReply, error)
	// ========== Inventory Management API ==========
	// ReserveInventory 预占库存
	ReserveInventory(ctx context.Context, in *ReserveInventoryRequest, opts ...grpc.CallOption) (*ReserveInventoryReply, error)
	// ConfirmInventory 确认库存
	ConfirmInventory(ctx context.Context, in *ConfirmInventoryRequest, opts ...grpc.CallOption) (*ConfirmInventoryReply, error)
	// CancelInventory 取消库存
	CancelInventory(ctx context.Context, in *CancelInventoryRequest, opts ...grpc.CallOption) (*CancelInventoryReply, error)
	// ListInventoryReservations 列出库存预占记录
	ListInventoryReservations(ctx context.Context, in *ListInventoryReservationsRequest, opts ...grpc.CallOption) (*ListInventoryReservationsReply, error)
	// ========== Task Completion Log API ==========
	// ListTaskCompletionLogs 列出任务完成日志
	ListTaskCompletionLogs(ctx context.Context, in *ListTaskCompletionLogsRequest, opts ...grpc.CallOption) (*ListTaskCompletionLogsReply, error)
	// GetTaskCompletionStats 获取任务完成统计
	GetTaskCompletionStats(ctx context.Context, in *GetTaskCompletionStatsRequest, opts ...grpc.CallOption) (*GetTaskCompletionStatsReply, error)
	// ========== Campaign Task Management API ==========
	// AddTaskToCampaign 将任务添加到活动
	AddTaskToCampaign(ctx context.Context, in *AddTaskToCampaignRequest, opts ...grpc.CallOption) (*AddTaskToCampaignReply, error)
	// RemoveTaskFromCampaign 从活动中移除任务
	RemoveTaskFromCampaign(ctx context.Context, in *RemoveTaskFromCampaignRequest, opts ...grpc.CallOption) (*RemoveTaskFromCampaignReply, error)
	// ListCampaignTasks 列出活动的所有任务
	ListCampaignTasks(ctx context.Context, in *ListCampaignTasksRequest, opts ...grpc.CallOption) (*ListCampaignTasksReply, error)
}

type marketingClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketingClient(cc grpc.ClientConnInterface) MarketingClient {
	return &marketingClient{cc}
}

func (c *marketingClient) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_CreateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*GetCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_GetCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaignsReply)
	err := c.cc.Invoke(ctx, Marketing_ListCampaigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...grpc.CallOption) (*UpdateCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_UpdateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_DeleteCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GenerateRedeemCodes(ctx context.Context, in *GenerateRedeemCodesRequest, opts ...grpc.CallOption) (*GenerateRedeemCodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRedeemCodesReply)
	err := c.cc.Invoke(ctx, Marketing_GenerateRedeemCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) RedeemCode(ctx context.Context, in *RedeemCodeRequest, opts ...grpc.CallOption) (*RedeemCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemCodeReply)
	err := c.cc.Invoke(ctx, Marketing_RedeemCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) AssignRedeemCode(ctx context.Context, in *AssignRedeemCodeRequest, opts ...grpc.CallOption) (*AssignRedeemCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignRedeemCodeReply)
	err := c.cc.Invoke(ctx, Marketing_AssignRedeemCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListRedeemCodes(ctx context.Context, in *ListRedeemCodesRequest, opts ...grpc.CallOption) (*ListRedeemCodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRedeemCodesReply)
	err := c.cc.Invoke(ctx, Marketing_ListRedeemCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetRedeemCode(ctx context.Context, in *GetRedeemCodeRequest, opts ...grpc.CallOption) (*GetRedeemCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRedeemCodeReply)
	err := c.cc.Invoke(ctx, Marketing_GetRedeemCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) CreateReward(ctx context.Context, in *CreateRewardRequest, opts ...grpc.CallOption) (*CreateRewardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRewardReply)
	err := c.cc.Invoke(ctx, Marketing_CreateReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetReward(ctx context.Context, in *GetRewardRequest, opts ...grpc.CallOption) (*GetRewardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRewardReply)
	err := c.cc.Invoke(ctx, Marketing_GetReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListRewards(ctx context.Context, in *ListRewardsRequest, opts ...grpc.CallOption) (*ListRewardsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRewardsReply)
	err := c.cc.Invoke(ctx, Marketing_ListRewards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) UpdateReward(ctx context.Context, in *UpdateRewardRequest, opts ...grpc.CallOption) (*UpdateRewardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRewardReply)
	err := c.cc.Invoke(ctx, Marketing_UpdateReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) DeleteReward(ctx context.Context, in *DeleteRewardRequest, opts ...grpc.CallOption) (*DeleteRewardReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRewardReply)
	err := c.cc.Invoke(ctx, Marketing_DeleteReward_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskReply)
	err := c.cc.Invoke(ctx, Marketing_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskReply)
	err := c.cc.Invoke(ctx, Marketing_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksReply)
	err := c.cc.Invoke(ctx, Marketing_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) UpdateTask(ctx context.Context, in *UpdateTaskRequest, opts ...grpc.CallOption) (*UpdateTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTaskReply)
	err := c.cc.Invoke(ctx, Marketing_UpdateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskReply)
	err := c.cc.Invoke(ctx, Marketing_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListTasksByCampaign(ctx context.Context, in *ListTasksByCampaignRequest, opts ...grpc.CallOption) (*ListTasksByCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksByCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_ListTasksByCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) CreateAudience(ctx context.Context, in *CreateAudienceRequest, opts ...grpc.CallOption) (*CreateAudienceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAudienceReply)
	err := c.cc.Invoke(ctx, Marketing_CreateAudience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetAudience(ctx context.Context, in *GetAudienceRequest, opts ...grpc.CallOption) (*GetAudienceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAudienceReply)
	err := c.cc.Invoke(ctx, Marketing_GetAudience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListAudiences(ctx context.Context, in *ListAudiencesRequest, opts ...grpc.CallOption) (*ListAudiencesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAudiencesReply)
	err := c.cc.Invoke(ctx, Marketing_ListAudiences_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) UpdateAudience(ctx context.Context, in *UpdateAudienceRequest, opts ...grpc.CallOption) (*UpdateAudienceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAudienceReply)
	err := c.cc.Invoke(ctx, Marketing_UpdateAudience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) DeleteAudience(ctx context.Context, in *DeleteAudienceRequest, opts ...grpc.CallOption) (*DeleteAudienceReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAudienceReply)
	err := c.cc.Invoke(ctx, Marketing_DeleteAudience_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListRewardGrants(ctx context.Context, in *ListRewardGrantsRequest, opts ...grpc.CallOption) (*ListRewardGrantsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRewardGrantsReply)
	err := c.cc.Invoke(ctx, Marketing_ListRewardGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetRewardGrant(ctx context.Context, in *GetRewardGrantRequest, opts ...grpc.CallOption) (*GetRewardGrantReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRewardGrantReply)
	err := c.cc.Invoke(ctx, Marketing_GetRewardGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) UpdateRewardGrantStatus(ctx context.Context, in *UpdateRewardGrantStatusRequest, opts ...grpc.CallOption) (*UpdateRewardGrantStatusReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRewardGrantStatusReply)
	err := c.cc.Invoke(ctx, Marketing_UpdateRewardGrantStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) TriggerTaskEvent(ctx context.Context, in *TriggerTaskEventRequest, opts ...grpc.CallOption) (*TriggerTaskEventReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerTaskEventReply)
	err := c.cc.Invoke(ctx, Marketing_TriggerTaskEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ReserveInventory(ctx context.Context, in *ReserveInventoryRequest, opts ...grpc.CallOption) (*ReserveInventoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReserveInventoryReply)
	err := c.cc.Invoke(ctx, Marketing_ReserveInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ConfirmInventory(ctx context.Context, in *ConfirmInventoryRequest, opts ...grpc.CallOption) (*ConfirmInventoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmInventoryReply)
	err := c.cc.Invoke(ctx, Marketing_ConfirmInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) CancelInventory(ctx context.Context, in *CancelInventoryRequest, opts ...grpc.CallOption) (*CancelInventoryReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelInventoryReply)
	err := c.cc.Invoke(ctx, Marketing_CancelInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListInventoryReservations(ctx context.Context, in *ListInventoryReservationsRequest, opts ...grpc.CallOption) (*ListInventoryReservationsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInventoryReservationsReply)
	err := c.cc.Invoke(ctx, Marketing_ListInventoryReservations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListTaskCompletionLogs(ctx context.Context, in *ListTaskCompletionLogsRequest, opts ...grpc.CallOption) (*ListTaskCompletionLogsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaskCompletionLogsReply)
	err := c.cc.Invoke(ctx, Marketing_ListTaskCompletionLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetTaskCompletionStats(ctx context.Context, in *GetTaskCompletionStatsRequest, opts ...grpc.CallOption) (*GetTaskCompletionStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskCompletionStatsReply)
	err := c.cc.Invoke(ctx, Marketing_GetTaskCompletionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) AddTaskToCampaign(ctx context.Context, in *AddTaskToCampaignRequest, opts ...grpc.CallOption) (*AddTaskToCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddTaskToCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_AddTaskToCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) RemoveTaskFromCampaign(ctx context.Context, in *RemoveTaskFromCampaignRequest, opts ...grpc.CallOption) (*RemoveTaskFromCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTaskFromCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_RemoveTaskFromCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListCampaignTasks(ctx context.Context, in *ListCampaignTasksRequest, opts ...grpc.CallOption) (*ListCampaignTasksReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaignTasksReply)
	err := c.cc.Invoke(ctx, Marketing_ListCampaignTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketingServer is the server API for Marketing service.
// All implementations must embed UnimplementedMarketingServer
// for forward compatibility.
//
// MarketingService 营销服务API
type MarketingServer interface {
	// CreateCampaign 创建营销活动
	CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignReply, error)
	// GetCampaign 获取营销活动
	GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignReply, error)
	// ListCampaigns 列出营销活动
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsReply, error)
	// UpdateCampaign 更新营销活动
	UpdateCampaign(context.Context, *UpdateCampaignRequest) (*UpdateCampaignReply, error)
	// DeleteCampaign 删除营销活动
	DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignReply, error)
	// GenerateRedeemCodes 生成兑换码
	GenerateRedeemCodes(context.Context, *GenerateRedeemCodesRequest) (*GenerateRedeemCodesReply, error)
	// RedeemCode 兑换码核销
	RedeemCode(context.Context, *RedeemCodeRequest) (*RedeemCodeReply, error)
	// AssignRedeemCode 分配兑换码
	AssignRedeemCode(context.Context, *AssignRedeemCodeRequest) (*AssignRedeemCodeReply, error)
	// ListRedeemCodes 列出兑换码
	ListRedeemCodes(context.Context, *ListRedeemCodesRequest) (*ListRedeemCodesReply, error)
	// GetRedeemCode 获取兑换码
	GetRedeemCode(context.Context, *GetRedeemCodeRequest) (*GetRedeemCodeReply, error)
	// ========== Reward API ==========
	// CreateReward 创建奖励
	CreateReward(context.Context, *CreateRewardRequest) (*CreateRewardReply, error)
	// GetReward 获取奖励
	GetReward(context.Context, *GetRewardRequest) (*GetRewardReply, error)
	// ListRewards 列出奖励
	ListRewards(context.Context, *ListRewardsRequest) (*ListRewardsReply, error)
	// UpdateReward 更新奖励
	UpdateReward(context.Context, *UpdateRewardRequest) (*UpdateRewardReply, error)
	// DeleteReward 删除奖励
	DeleteReward(context.Context, *DeleteRewardRequest) (*DeleteRewardReply, error)
	// ========== Task API ==========
	// CreateTask 创建任务
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskReply, error)
	// GetTask 获取任务
	GetTask(context.Context, *GetTaskRequest) (*GetTaskReply, error)
	// ListTasks 列出任务
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error)
	// UpdateTask 更新任务
	UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskReply, error)
	// DeleteTask 删除任务
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskReply, error)
	// ListTasksByCampaign 根据活动列出任务
	ListTasksByCampaign(context.Context, *ListTasksByCampaignRequest) (*ListTasksByCampaignReply, error)
	// ========== Audience API ==========
	// CreateAudience 创建受众
	CreateAudience(context.Context, *CreateAudienceRequest) (*CreateAudienceReply, error)
	// GetAudience 获取受众
	GetAudience(context.Context, *GetAudienceRequest) (*GetAudienceReply, error)
	// ListAudiences 列出受众
	ListAudiences(context.Context, *ListAudiencesRequest) (*ListAudiencesReply, error)
	// UpdateAudience 更新受众
	UpdateAudience(context.Context, *UpdateAudienceRequest) (*UpdateAudienceReply, error)
	// DeleteAudience 删除受众
	DeleteAudience(context.Context, *DeleteAudienceRequest) (*DeleteAudienceReply, error)
	// ========== RewardGrant API ==========
	// ListRewardGrants 列出奖励发放记录
	ListRewardGrants(context.Context, *ListRewardGrantsRequest) (*ListRewardGrantsReply, error)
	// GetRewardGrant 获取奖励发放记录
	GetRewardGrant(context.Context, *GetRewardGrantRequest) (*GetRewardGrantReply, error)
	// UpdateRewardGrantStatus 更新发放状态
	UpdateRewardGrantStatus(context.Context, *UpdateRewardGrantStatusRequest) (*UpdateRewardGrantStatusReply, error)
	// ========== Task Event API ==========
	// TriggerTaskEvent 触发任务事件
	TriggerTaskEvent(context.Context, *TriggerTaskEventRequest) (*TriggerTaskEventReply, error)
	// ========== Inventory Management API ==========
	// ReserveInventory 预占库存
	ReserveInventory(context.Context, *ReserveInventoryRequest) (*ReserveInventoryReply, error)
	// ConfirmInventory 确认库存
	ConfirmInventory(context.Context, *ConfirmInventoryRequest) (*ConfirmInventoryReply, error)
	// CancelInventory 取消库存
	CancelInventory(context.Context, *CancelInventoryRequest) (*CancelInventoryReply, error)
	// ListInventoryReservations 列出库存预占记录
	ListInventoryReservations(context.Context, *ListInventoryReservationsRequest) (*ListInventoryReservationsReply, error)
	// ========== Task Completion Log API ==========
	// ListTaskCompletionLogs 列出任务完成日志
	ListTaskCompletionLogs(context.Context, *ListTaskCompletionLogsRequest) (*ListTaskCompletionLogsReply, error)
	// GetTaskCompletionStats 获取任务完成统计
	GetTaskCompletionStats(context.Context, *GetTaskCompletionStatsRequest) (*GetTaskCompletionStatsReply, error)
	// ========== Campaign Task Management API ==========
	// AddTaskToCampaign 将任务添加到活动
	AddTaskToCampaign(context.Context, *AddTaskToCampaignRequest) (*AddTaskToCampaignReply, error)
	// RemoveTaskFromCampaign 从活动中移除任务
	RemoveTaskFromCampaign(context.Context, *RemoveTaskFromCampaignRequest) (*RemoveTaskFromCampaignReply, error)
	// ListCampaignTasks 列出活动的所有任务
	ListCampaignTasks(context.Context, *ListCampaignTasksRequest) (*ListCampaignTasksReply, error)
	mustEmbedUnimplementedMarketingServer()
}

// UnimplementedMarketingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketingServer struct{}

func (UnimplementedMarketingServer) CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (UnimplementedMarketingServer) GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCampaign not implemented")
}
func (UnimplementedMarketingServer) ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCampaigns not implemented")
}
func (UnimplementedMarketingServer) UpdateCampaign(context.Context, *UpdateCampaignRequest) (*UpdateCampaignReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCampaign not implemented")
}
func (UnimplementedMarketingServer) DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCampaign not implemented")
}
func (UnimplementedMarketingServer) GenerateRedeemCodes(context.Context, *GenerateRedeemCodesRequest) (*GenerateRedeemCodesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateRedeemCodes not implemented")
}
func (UnimplementedMarketingServer) RedeemCode(context.Context, *RedeemCodeRequest) (*RedeemCodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RedeemCode not implemented")
}
func (UnimplementedMarketingServer) AssignRedeemCode(context.Context, *AssignRedeemCodeRequest) (*AssignRedeemCodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AssignRedeemCode not implemented")
}
func (UnimplementedMarketingServer) ListRedeemCodes(context.Context, *ListRedeemCodesRequest) (*ListRedeemCodesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRedeemCodes not implemented")
}
func (UnimplementedMarketingServer) GetRedeemCode(context.Context, *GetRedeemCodeRequest) (*GetRedeemCodeReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRedeemCode not implemented")
}
func (UnimplementedMarketingServer) CreateReward(context.Context, *CreateRewardRequest) (*CreateRewardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReward not implemented")
}
func (UnimplementedMarketingServer) GetReward(context.Context, *GetRewardRequest) (*GetRewardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReward not implemented")
}
func (UnimplementedMarketingServer) ListRewards(context.Context, *ListRewardsRequest) (*ListRewardsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRewards not implemented")
}
func (UnimplementedMarketingServer) UpdateReward(context.Context, *UpdateRewardRequest) (*UpdateRewardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateReward not implemented")
}
func (UnimplementedMarketingServer) DeleteReward(context.Context, *DeleteRewardRequest) (*DeleteRewardReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteReward not implemented")
}
func (UnimplementedMarketingServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedMarketingServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedMarketingServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedMarketingServer) UpdateTask(context.Context, *UpdateTaskRequest) (*UpdateTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTask not implemented")
}
func (UnimplementedMarketingServer) DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedMarketingServer) ListTasksByCampaign(context.Context, *ListTasksByCampaignRequest) (*ListTasksByCampaignReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasksByCampaign not implemented")
}
func (UnimplementedMarketingServer) CreateAudience(context.Context, *CreateAudienceRequest) (*CreateAudienceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAudience not implemented")
}
func (UnimplementedMarketingServer) GetAudience(context.Context, *GetAudienceRequest) (*GetAudienceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAudience not implemented")
}
func (UnimplementedMarketingServer) ListAudiences(context.Context, *ListAudiencesRequest) (*ListAudiencesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAudiences not implemented")
}
func (UnimplementedMarketingServer) UpdateAudience(context.Context, *UpdateAudienceRequest) (*UpdateAudienceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAudience not implemented")
}
func (UnimplementedMarketingServer) DeleteAudience(context.Context, *DeleteAudienceRequest) (*DeleteAudienceReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAudience not implemented")
}
func (UnimplementedMarketingServer) ListRewardGrants(context.Context, *ListRewardGrantsRequest) (*ListRewardGrantsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRewardGrants not implemented")
}
func (UnimplementedMarketingServer) GetRewardGrant(context.Context, *GetRewardGrantRequest) (*GetRewardGrantReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRewardGrant not implemented")
}
func (UnimplementedMarketingServer) UpdateRewardGrantStatus(context.Context, *UpdateRewardGrantStatusRequest) (*UpdateRewardGrantStatusReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRewardGrantStatus not implemented")
}
func (UnimplementedMarketingServer) TriggerTaskEvent(context.Context, *TriggerTaskEventRequest) (*TriggerTaskEventReply, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerTaskEvent not implemented")
}
func (UnimplementedMarketingServer) ReserveInventory(context.Context, *ReserveInventoryRequest) (*ReserveInventoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ReserveInventory not implemented")
}
func (UnimplementedMarketingServer) ConfirmInventory(context.Context, *ConfirmInventoryRequest) (*ConfirmInventoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmInventory not implemented")
}
func (UnimplementedMarketingServer) CancelInventory(context.Context, *CancelInventoryRequest) (*CancelInventoryReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInventory not implemented")
}
func (UnimplementedMarketingServer) ListInventoryReservations(context.Context, *ListInventoryReservationsRequest) (*ListInventoryReservationsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInventoryReservations not implemented")
}
func (UnimplementedMarketingServer) ListTaskCompletionLogs(context.Context, *ListTaskCompletionLogsRequest) (*ListTaskCompletionLogsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTaskCompletionLogs not implemented")
}
func (UnimplementedMarketingServer) GetTaskCompletionStats(context.Context, *GetTaskCompletionStatsRequest) (*GetTaskCompletionStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskCompletionStats not implemented")
}
func (UnimplementedMarketingServer) AddTaskToCampaign(context.Context, *AddTaskToCampaignRequest) (*AddTaskToCampaignReply, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTaskToCampaign not implemented")
}
func (UnimplementedMarketingServer) RemoveTaskFromCampaign(context.Context, *RemoveTaskFromCampaignRequest) (*RemoveTaskFromCampaignReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTaskFromCampaign not implemented")
}
func (UnimplementedMarketingServer) ListCampaignTasks(context.Context, *ListCampaignTasksRequest) (*ListCampaignTasksReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCampaignTasks not implemented")
}
func (UnimplementedMarketingServer) mustEmbedUnimplementedMarketingServer() {}
func (UnimplementedMarketingServer) testEmbeddedByValue()                   {}

// UnsafeMarketingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketingServer will
// result in compilation errors.
type UnsafeMarketingServer interface {
	mustEmbedUnimplementedMarketingServer()
}

func RegisterMarketingServer(s grpc.ServiceRegistrar, srv MarketingServer) {
	// If the following call panics, it indicates UnimplementedMarketingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Marketing_ServiceDesc, srv)
}

func _Marketing_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_CreateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CreateCampaign(ctx, req.(*CreateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetCampaign(ctx, req.(*GetCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListCampaigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListCampaigns(ctx, req.(*ListCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_UpdateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).UpdateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_UpdateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).UpdateCampaign(ctx, req.(*UpdateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_DeleteCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).DeleteCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_DeleteCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).DeleteCampaign(ctx, req.(*DeleteCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GenerateRedeemCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRedeemCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GenerateRedeemCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GenerateRedeemCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GenerateRedeemCodes(ctx, req.(*GenerateRedeemCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_RedeemCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).RedeemCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_RedeemCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).RedeemCode(ctx, req.(*RedeemCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_AssignRedeemCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRedeemCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).AssignRedeemCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_AssignRedeemCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).AssignRedeemCode(ctx, req.(*AssignRedeemCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListRedeemCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRedeemCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListRedeemCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListRedeemCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListRedeemCodes(ctx, req.(*ListRedeemCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetRedeemCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedeemCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetRedeemCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetRedeemCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetRedeemCode(ctx, req.(*GetRedeemCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_CreateReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CreateReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_CreateReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CreateReward(ctx, req.(*CreateRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetReward(ctx, req.(*GetRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListRewards(ctx, req.(*ListRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_UpdateReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).UpdateReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_UpdateReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).UpdateReward(ctx, req.(*UpdateRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_DeleteReward_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRewardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).DeleteReward(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_DeleteReward_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).DeleteReward(ctx, req.(*DeleteRewardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_UpdateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).UpdateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_UpdateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).UpdateTask(ctx, req.(*UpdateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListTasksByCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksByCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListTasksByCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListTasksByCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListTasksByCampaign(ctx, req.(*ListTasksByCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_CreateAudience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAudienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CreateAudience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_CreateAudience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CreateAudience(ctx, req.(*CreateAudienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetAudience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAudienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetAudience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetAudience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetAudience(ctx, req.(*GetAudienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListAudiences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAudiencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListAudiences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListAudiences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListAudiences(ctx, req.(*ListAudiencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_UpdateAudience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAudienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).UpdateAudience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_UpdateAudience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).UpdateAudience(ctx, req.(*UpdateAudienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_DeleteAudience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAudienceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).DeleteAudience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_DeleteAudience_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).DeleteAudience(ctx, req.(*DeleteAudienceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListRewardGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRewardGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListRewardGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListRewardGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListRewardGrants(ctx, req.(*ListRewardGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetRewardGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRewardGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetRewardGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetRewardGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetRewardGrant(ctx, req.(*GetRewardGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_UpdateRewardGrantStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRewardGrantStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).UpdateRewardGrantStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_UpdateRewardGrantStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).UpdateRewardGrantStatus(ctx, req.(*UpdateRewardGrantStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_TriggerTaskEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerTaskEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).TriggerTaskEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_TriggerTaskEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).TriggerTaskEvent(ctx, req.(*TriggerTaskEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ReserveInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReserveInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ReserveInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ReserveInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ReserveInventory(ctx, req.(*ReserveInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ConfirmInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ConfirmInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ConfirmInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ConfirmInventory(ctx, req.(*ConfirmInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_CancelInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CancelInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_CancelInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CancelInventory(ctx, req.(*CancelInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListInventoryReservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInventoryReservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListInventoryReservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListInventoryReservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListInventoryReservations(ctx, req.(*ListInventoryReservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListTaskCompletionLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskCompletionLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListTaskCompletionLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListTaskCompletionLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListTaskCompletionLogs(ctx, req.(*ListTaskCompletionLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetTaskCompletionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskCompletionStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetTaskCompletionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetTaskCompletionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetTaskCompletionStats(ctx, req.(*GetTaskCompletionStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_AddTaskToCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskToCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).AddTaskToCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_AddTaskToCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).AddTaskToCampaign(ctx, req.(*AddTaskToCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_RemoveTaskFromCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTaskFromCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).RemoveTaskFromCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_RemoveTaskFromCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).RemoveTaskFromCampaign(ctx, req.(*RemoveTaskFromCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListCampaignTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCampaignTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListCampaignTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListCampaignTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListCampaignTasks(ctx, req.(*ListCampaignTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Marketing_ServiceDesc is the grpc.ServiceDesc for Marketing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marketing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.marketing_service.v1.Marketing",
	HandlerType: (*MarketingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCampaign",
			Handler:    _Marketing_CreateCampaign_Handler,
		},
		{
			MethodName: "GetCampaign",
			Handler:    _Marketing_GetCampaign_Handler,
		},
		{
			MethodName: "ListCampaigns",
			Handler:    _Marketing_ListCampaigns_Handler,
		},
		{
			MethodName: "UpdateCampaign",
			Handler:    _Marketing_UpdateCampaign_Handler,
		},
		{
			MethodName: "DeleteCampaign",
			Handler:    _Marketing_DeleteCampaign_Handler,
		},
		{
			MethodName: "GenerateRedeemCodes",
			Handler:    _Marketing_GenerateRedeemCodes_Handler,
		},
		{
			MethodName: "RedeemCode",
			Handler:    _Marketing_RedeemCode_Handler,
		},
		{
			MethodName: "AssignRedeemCode",
			Handler:    _Marketing_AssignRedeemCode_Handler,
		},
		{
			MethodName: "ListRedeemCodes",
			Handler:    _Marketing_ListRedeemCodes_Handler,
		},
		{
			MethodName: "GetRedeemCode",
			Handler:    _Marketing_GetRedeemCode_Handler,
		},
		{
			MethodName: "CreateReward",
			Handler:    _Marketing_CreateReward_Handler,
		},
		{
			MethodName: "GetReward",
			Handler:    _Marketing_GetReward_Handler,
		},
		{
			MethodName: "ListRewards",
			Handler:    _Marketing_ListRewards_Handler,
		},
		{
			MethodName: "UpdateReward",
			Handler:    _Marketing_UpdateReward_Handler,
		},
		{
			MethodName: "DeleteReward",
			Handler:    _Marketing_DeleteReward_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _Marketing_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _Marketing_GetTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _Marketing_ListTasks_Handler,
		},
		{
			MethodName: "UpdateTask",
			Handler:    _Marketing_UpdateTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _Marketing_DeleteTask_Handler,
		},
		{
			MethodName: "ListTasksByCampaign",
			Handler:    _Marketing_ListTasksByCampaign_Handler,
		},
		{
			MethodName: "CreateAudience",
			Handler:    _Marketing_CreateAudience_Handler,
		},
		{
			MethodName: "GetAudience",
			Handler:    _Marketing_GetAudience_Handler,
		},
		{
			MethodName: "ListAudiences",
			Handler:    _Marketing_ListAudiences_Handler,
		},
		{
			MethodName: "UpdateAudience",
			Handler:    _Marketing_UpdateAudience_Handler,
		},
		{
			MethodName: "DeleteAudience",
			Handler:    _Marketing_DeleteAudience_Handler,
		},
		{
			MethodName: "ListRewardGrants",
			Handler:    _Marketing_ListRewardGrants_Handler,
		},
		{
			MethodName: "GetRewardGrant",
			Handler:    _Marketing_GetRewardGrant_Handler,
		},
		{
			MethodName: "UpdateRewardGrantStatus",
			Handler:    _Marketing_UpdateRewardGrantStatus_Handler,
		},
		{
			MethodName: "TriggerTaskEvent",
			Handler:    _Marketing_TriggerTaskEvent_Handler,
		},
		{
			MethodName: "ReserveInventory",
			Handler:    _Marketing_ReserveInventory_Handler,
		},
		{
			MethodName: "ConfirmInventory",
			Handler:    _Marketing_ConfirmInventory_Handler,
		},
		{
			MethodName: "CancelInventory",
			Handler:    _Marketing_CancelInventory_Handler,
		},
		{
			MethodName: "ListInventoryReservations",
			Handler:    _Marketing_ListInventoryReservations_Handler,
		},
		{
			MethodName: "ListTaskCompletionLogs",
			Handler:    _Marketing_ListTaskCompletionLogs_Handler,
		},
		{
			MethodName: "GetTaskCompletionStats",
			Handler:    _Marketing_GetTaskCompletionStats_Handler,
		},
		{
			MethodName: "AddTaskToCampaign",
			Handler:    _Marketing_AddTaskToCampaign_Handler,
		},
		{
			MethodName: "RemoveTaskFromCampaign",
			Handler:    _Marketing_RemoveTaskFromCampaign_Handler,
		},
		{
			MethodName: "ListCampaignTasks",
			Handler:    _Marketing_ListCampaignTasks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketing.proto",
}
