// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: platform/marketing_service/v1/marketing.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Marketing_CreateCampaign_FullMethodName      = "/platform.marketing_service.v1.Marketing/CreateCampaign"
	Marketing_GetCampaign_FullMethodName         = "/platform.marketing_service.v1.Marketing/GetCampaign"
	Marketing_ListCampaigns_FullMethodName       = "/platform.marketing_service.v1.Marketing/ListCampaigns"
	Marketing_UpdateCampaign_FullMethodName      = "/platform.marketing_service.v1.Marketing/UpdateCampaign"
	Marketing_DeleteCampaign_FullMethodName      = "/platform.marketing_service.v1.Marketing/DeleteCampaign"
	Marketing_GenerateRedeemCodes_FullMethodName = "/platform.marketing_service.v1.Marketing/GenerateRedeemCodes"
	Marketing_RedeemCode_FullMethodName          = "/platform.marketing_service.v1.Marketing/RedeemCode"
	Marketing_AssignRedeemCode_FullMethodName    = "/platform.marketing_service.v1.Marketing/AssignRedeemCode"
	Marketing_ListRedeemCodes_FullMethodName     = "/platform.marketing_service.v1.Marketing/ListRedeemCodes"
	Marketing_GetRedeemCode_FullMethodName       = "/platform.marketing_service.v1.Marketing/GetRedeemCode"
)

// MarketingClient is the client API for Marketing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketingService 营销服务API
type MarketingClient interface {
	// CreateCampaign 创建营销活动
	CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignReply, error)
	// GetCampaign 获取营销活动
	GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*GetCampaignReply, error)
	// ListCampaigns 列出营销活动
	ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsReply, error)
	// UpdateCampaign 更新营销活动
	UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...grpc.CallOption) (*UpdateCampaignReply, error)
	// DeleteCampaign 删除营销活动
	DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteCampaignReply, error)
	// GenerateRedeemCodes 生成兑换码
	GenerateRedeemCodes(ctx context.Context, in *GenerateRedeemCodesRequest, opts ...grpc.CallOption) (*GenerateRedeemCodesReply, error)
	// RedeemCode 兑换码核销
	RedeemCode(ctx context.Context, in *RedeemCodeRequest, opts ...grpc.CallOption) (*RedeemCodeReply, error)
	// AssignRedeemCode 分配兑换码
	AssignRedeemCode(ctx context.Context, in *AssignRedeemCodeRequest, opts ...grpc.CallOption) (*AssignRedeemCodeReply, error)
	// ListRedeemCodes 列出兑换码
	ListRedeemCodes(ctx context.Context, in *ListRedeemCodesRequest, opts ...grpc.CallOption) (*ListRedeemCodesReply, error)
	// GetRedeemCode 获取兑换码
	GetRedeemCode(ctx context.Context, in *GetRedeemCodeRequest, opts ...grpc.CallOption) (*GetRedeemCodeReply, error)
}

type marketingClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketingClient(cc grpc.ClientConnInterface) MarketingClient {
	return &marketingClient{cc}
}

func (c *marketingClient) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...grpc.CallOption) (*CreateCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_CreateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...grpc.CallOption) (*GetCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_GetCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...grpc.CallOption) (*ListCampaignsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCampaignsReply)
	err := c.cc.Invoke(ctx, Marketing_ListCampaigns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...grpc.CallOption) (*UpdateCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_UpdateCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...grpc.CallOption) (*DeleteCampaignReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCampaignReply)
	err := c.cc.Invoke(ctx, Marketing_DeleteCampaign_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GenerateRedeemCodes(ctx context.Context, in *GenerateRedeemCodesRequest, opts ...grpc.CallOption) (*GenerateRedeemCodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRedeemCodesReply)
	err := c.cc.Invoke(ctx, Marketing_GenerateRedeemCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) RedeemCode(ctx context.Context, in *RedeemCodeRequest, opts ...grpc.CallOption) (*RedeemCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedeemCodeReply)
	err := c.cc.Invoke(ctx, Marketing_RedeemCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) AssignRedeemCode(ctx context.Context, in *AssignRedeemCodeRequest, opts ...grpc.CallOption) (*AssignRedeemCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AssignRedeemCodeReply)
	err := c.cc.Invoke(ctx, Marketing_AssignRedeemCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListRedeemCodes(ctx context.Context, in *ListRedeemCodesRequest, opts ...grpc.CallOption) (*ListRedeemCodesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRedeemCodesReply)
	err := c.cc.Invoke(ctx, Marketing_ListRedeemCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetRedeemCode(ctx context.Context, in *GetRedeemCodeRequest, opts ...grpc.CallOption) (*GetRedeemCodeReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRedeemCodeReply)
	err := c.cc.Invoke(ctx, Marketing_GetRedeemCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketingServer is the server API for Marketing service.
// All implementations must embed UnimplementedMarketingServer
// for forward compatibility.
//
// MarketingService 营销服务API
type MarketingServer interface {
	// CreateCampaign 创建营销活动
	CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignReply, error)
	// GetCampaign 获取营销活动
	GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignReply, error)
	// ListCampaigns 列出营销活动
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsReply, error)
	// UpdateCampaign 更新营销活动
	UpdateCampaign(context.Context, *UpdateCampaignRequest) (*UpdateCampaignReply, error)
	// DeleteCampaign 删除营销活动
	DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignReply, error)
	// GenerateRedeemCodes 生成兑换码
	GenerateRedeemCodes(context.Context, *GenerateRedeemCodesRequest) (*GenerateRedeemCodesReply, error)
	// RedeemCode 兑换码核销
	RedeemCode(context.Context, *RedeemCodeRequest) (*RedeemCodeReply, error)
	// AssignRedeemCode 分配兑换码
	AssignRedeemCode(context.Context, *AssignRedeemCodeRequest) (*AssignRedeemCodeReply, error)
	// ListRedeemCodes 列出兑换码
	ListRedeemCodes(context.Context, *ListRedeemCodesRequest) (*ListRedeemCodesReply, error)
	// GetRedeemCode 获取兑换码
	GetRedeemCode(context.Context, *GetRedeemCodeRequest) (*GetRedeemCodeReply, error)
	mustEmbedUnimplementedMarketingServer()
}

// UnimplementedMarketingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketingServer struct{}

func (UnimplementedMarketingServer) CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCampaign not implemented")
}
func (UnimplementedMarketingServer) GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCampaign not implemented")
}
func (UnimplementedMarketingServer) ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCampaigns not implemented")
}
func (UnimplementedMarketingServer) UpdateCampaign(context.Context, *UpdateCampaignRequest) (*UpdateCampaignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCampaign not implemented")
}
func (UnimplementedMarketingServer) DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCampaign not implemented")
}
func (UnimplementedMarketingServer) GenerateRedeemCodes(context.Context, *GenerateRedeemCodesRequest) (*GenerateRedeemCodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRedeemCodes not implemented")
}
func (UnimplementedMarketingServer) RedeemCode(context.Context, *RedeemCodeRequest) (*RedeemCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RedeemCode not implemented")
}
func (UnimplementedMarketingServer) AssignRedeemCode(context.Context, *AssignRedeemCodeRequest) (*AssignRedeemCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignRedeemCode not implemented")
}
func (UnimplementedMarketingServer) ListRedeemCodes(context.Context, *ListRedeemCodesRequest) (*ListRedeemCodesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRedeemCodes not implemented")
}
func (UnimplementedMarketingServer) GetRedeemCode(context.Context, *GetRedeemCodeRequest) (*GetRedeemCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRedeemCode not implemented")
}
func (UnimplementedMarketingServer) mustEmbedUnimplementedMarketingServer() {}
func (UnimplementedMarketingServer) testEmbeddedByValue()                   {}

// UnsafeMarketingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketingServer will
// result in compilation errors.
type UnsafeMarketingServer interface {
	mustEmbedUnimplementedMarketingServer()
}

func RegisterMarketingServer(s grpc.ServiceRegistrar, srv MarketingServer) {
	// If the following call pancis, it indicates UnimplementedMarketingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Marketing_ServiceDesc, srv)
}

func _Marketing_CreateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CreateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_CreateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CreateCampaign(ctx, req.(*CreateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetCampaign(ctx, req.(*GetCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListCampaigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCampaignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListCampaigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListCampaigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListCampaigns(ctx, req.(*ListCampaignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_UpdateCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).UpdateCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_UpdateCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).UpdateCampaign(ctx, req.(*UpdateCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_DeleteCampaign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCampaignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).DeleteCampaign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_DeleteCampaign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).DeleteCampaign(ctx, req.(*DeleteCampaignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GenerateRedeemCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRedeemCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GenerateRedeemCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GenerateRedeemCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GenerateRedeemCodes(ctx, req.(*GenerateRedeemCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_RedeemCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedeemCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).RedeemCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_RedeemCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).RedeemCode(ctx, req.(*RedeemCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_AssignRedeemCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRedeemCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).AssignRedeemCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_AssignRedeemCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).AssignRedeemCode(ctx, req.(*AssignRedeemCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListRedeemCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRedeemCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListRedeemCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListRedeemCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListRedeemCodes(ctx, req.(*ListRedeemCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetRedeemCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRedeemCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetRedeemCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetRedeemCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetRedeemCode(ctx, req.(*GetRedeemCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Marketing_ServiceDesc is the grpc.ServiceDesc for Marketing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marketing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.marketing_service.v1.Marketing",
	HandlerType: (*MarketingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCampaign",
			Handler:    _Marketing_CreateCampaign_Handler,
		},
		{
			MethodName: "GetCampaign",
			Handler:    _Marketing_GetCampaign_Handler,
		},
		{
			MethodName: "ListCampaigns",
			Handler:    _Marketing_ListCampaigns_Handler,
		},
		{
			MethodName: "UpdateCampaign",
			Handler:    _Marketing_UpdateCampaign_Handler,
		},
		{
			MethodName: "DeleteCampaign",
			Handler:    _Marketing_DeleteCampaign_Handler,
		},
		{
			MethodName: "GenerateRedeemCodes",
			Handler:    _Marketing_GenerateRedeemCodes_Handler,
		},
		{
			MethodName: "RedeemCode",
			Handler:    _Marketing_RedeemCode_Handler,
		},
		{
			MethodName: "AssignRedeemCode",
			Handler:    _Marketing_AssignRedeemCode_Handler,
		},
		{
			MethodName: "ListRedeemCodes",
			Handler:    _Marketing_ListRedeemCodes_Handler,
		},
		{
			MethodName: "GetRedeemCode",
			Handler:    _Marketing_GetRedeemCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/marketing_service/v1/marketing.proto",
}
