// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: marketing.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Marketing_CreateCoupon_FullMethodName           = "/platform.marketing_service.v1.Marketing/CreateCoupon"
	Marketing_GetCoupon_FullMethodName              = "/platform.marketing_service.v1.Marketing/GetCoupon"
	Marketing_ListCoupons_FullMethodName            = "/platform.marketing_service.v1.Marketing/ListCoupons"
	Marketing_UpdateCoupon_FullMethodName           = "/platform.marketing_service.v1.Marketing/UpdateCoupon"
	Marketing_DeleteCoupon_FullMethodName           = "/platform.marketing_service.v1.Marketing/DeleteCoupon"
	Marketing_ValidateCoupon_FullMethodName         = "/platform.marketing_service.v1.Marketing/ValidateCoupon"
	Marketing_UseCoupon_FullMethodName              = "/platform.marketing_service.v1.Marketing/UseCoupon"
	Marketing_GetCouponStats_FullMethodName         = "/platform.marketing_service.v1.Marketing/GetCouponStats"
	Marketing_ListCouponUsages_FullMethodName       = "/platform.marketing_service.v1.Marketing/ListCouponUsages"
	Marketing_GetCouponsSummaryStats_FullMethodName = "/platform.marketing_service.v1.Marketing/GetCouponsSummaryStats"
)

// MarketingClient is the client API for Marketing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MarketingService 营销服务API（极简重构版：仅保留优惠券功能）
type MarketingClient interface {
	// ========== Coupon Management API (供开发者控制台使用) ==========
	// CreateCoupon 创建优惠券
	CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*CreateCouponReply, error)
	// GetCoupon 获取优惠券
	GetCoupon(ctx context.Context, in *GetCouponRequest, opts ...grpc.CallOption) (*GetCouponReply, error)
	// ListCoupons 列出优惠券
	ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsReply, error)
	// UpdateCoupon 更新优惠券
	UpdateCoupon(ctx context.Context, in *UpdateCouponRequest, opts ...grpc.CallOption) (*UpdateCouponReply, error)
	// DeleteCoupon 删除优惠券
	DeleteCoupon(ctx context.Context, in *DeleteCouponRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// ValidateCoupon 验证优惠券 (供 Payment Service 调用)
	ValidateCoupon(ctx context.Context, in *ValidateCouponRequest, opts ...grpc.CallOption) (*ValidateCouponReply, error)
	// UseCoupon 使用优惠券 (供 Payment Service 调用)
	UseCoupon(ctx context.Context, in *UseCouponRequest, opts ...grpc.CallOption) (*UseCouponReply, error)
	// GetCouponStats 获取优惠券统计
	GetCouponStats(ctx context.Context, in *GetCouponStatsRequest, opts ...grpc.CallOption) (*GetCouponStatsReply, error)
	// ListCouponUsages 列出优惠券使用记录
	ListCouponUsages(ctx context.Context, in *ListCouponUsagesRequest, opts ...grpc.CallOption) (*ListCouponUsagesReply, error)
	// GetCouponsSummaryStats 获取所有优惠券汇总统计（供营销效果仪表板使用）
	GetCouponsSummaryStats(ctx context.Context, in *GetCouponsSummaryStatsRequest, opts ...grpc.CallOption) (*GetCouponsSummaryStatsReply, error)
}

type marketingClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketingClient(cc grpc.ClientConnInterface) MarketingClient {
	return &marketingClient{cc}
}

func (c *marketingClient) CreateCoupon(ctx context.Context, in *CreateCouponRequest, opts ...grpc.CallOption) (*CreateCouponReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCouponReply)
	err := c.cc.Invoke(ctx, Marketing_CreateCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetCoupon(ctx context.Context, in *GetCouponRequest, opts ...grpc.CallOption) (*GetCouponReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCouponReply)
	err := c.cc.Invoke(ctx, Marketing_GetCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListCoupons(ctx context.Context, in *ListCouponsRequest, opts ...grpc.CallOption) (*ListCouponsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouponsReply)
	err := c.cc.Invoke(ctx, Marketing_ListCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) UpdateCoupon(ctx context.Context, in *UpdateCouponRequest, opts ...grpc.CallOption) (*UpdateCouponReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCouponReply)
	err := c.cc.Invoke(ctx, Marketing_UpdateCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) DeleteCoupon(ctx context.Context, in *DeleteCouponRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, Marketing_DeleteCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ValidateCoupon(ctx context.Context, in *ValidateCouponRequest, opts ...grpc.CallOption) (*ValidateCouponReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCouponReply)
	err := c.cc.Invoke(ctx, Marketing_ValidateCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) UseCoupon(ctx context.Context, in *UseCouponRequest, opts ...grpc.CallOption) (*UseCouponReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseCouponReply)
	err := c.cc.Invoke(ctx, Marketing_UseCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetCouponStats(ctx context.Context, in *GetCouponStatsRequest, opts ...grpc.CallOption) (*GetCouponStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCouponStatsReply)
	err := c.cc.Invoke(ctx, Marketing_GetCouponStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) ListCouponUsages(ctx context.Context, in *ListCouponUsagesRequest, opts ...grpc.CallOption) (*ListCouponUsagesReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouponUsagesReply)
	err := c.cc.Invoke(ctx, Marketing_ListCouponUsages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketingClient) GetCouponsSummaryStats(ctx context.Context, in *GetCouponsSummaryStatsRequest, opts ...grpc.CallOption) (*GetCouponsSummaryStatsReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCouponsSummaryStatsReply)
	err := c.cc.Invoke(ctx, Marketing_GetCouponsSummaryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketingServer is the server API for Marketing service.
// All implementations must embed UnimplementedMarketingServer
// for forward compatibility.
//
// MarketingService 营销服务API（极简重构版：仅保留优惠券功能）
type MarketingServer interface {
	// ========== Coupon Management API (供开发者控制台使用) ==========
	// CreateCoupon 创建优惠券
	CreateCoupon(context.Context, *CreateCouponRequest) (*CreateCouponReply, error)
	// GetCoupon 获取优惠券
	GetCoupon(context.Context, *GetCouponRequest) (*GetCouponReply, error)
	// ListCoupons 列出优惠券
	ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsReply, error)
	// UpdateCoupon 更新优惠券
	UpdateCoupon(context.Context, *UpdateCouponRequest) (*UpdateCouponReply, error)
	// DeleteCoupon 删除优惠券
	DeleteCoupon(context.Context, *DeleteCouponRequest) (*emptypb.Empty, error)
	// ValidateCoupon 验证优惠券 (供 Payment Service 调用)
	ValidateCoupon(context.Context, *ValidateCouponRequest) (*ValidateCouponReply, error)
	// UseCoupon 使用优惠券 (供 Payment Service 调用)
	UseCoupon(context.Context, *UseCouponRequest) (*UseCouponReply, error)
	// GetCouponStats 获取优惠券统计
	GetCouponStats(context.Context, *GetCouponStatsRequest) (*GetCouponStatsReply, error)
	// ListCouponUsages 列出优惠券使用记录
	ListCouponUsages(context.Context, *ListCouponUsagesRequest) (*ListCouponUsagesReply, error)
	// GetCouponsSummaryStats 获取所有优惠券汇总统计（供营销效果仪表板使用）
	GetCouponsSummaryStats(context.Context, *GetCouponsSummaryStatsRequest) (*GetCouponsSummaryStatsReply, error)
	mustEmbedUnimplementedMarketingServer()
}

// UnimplementedMarketingServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketingServer struct{}

func (UnimplementedMarketingServer) CreateCoupon(context.Context, *CreateCouponRequest) (*CreateCouponReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCoupon not implemented")
}
func (UnimplementedMarketingServer) GetCoupon(context.Context, *GetCouponRequest) (*GetCouponReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCoupon not implemented")
}
func (UnimplementedMarketingServer) ListCoupons(context.Context, *ListCouponsRequest) (*ListCouponsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCoupons not implemented")
}
func (UnimplementedMarketingServer) UpdateCoupon(context.Context, *UpdateCouponRequest) (*UpdateCouponReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCoupon not implemented")
}
func (UnimplementedMarketingServer) DeleteCoupon(context.Context, *DeleteCouponRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCoupon not implemented")
}
func (UnimplementedMarketingServer) ValidateCoupon(context.Context, *ValidateCouponRequest) (*ValidateCouponReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCoupon not implemented")
}
func (UnimplementedMarketingServer) UseCoupon(context.Context, *UseCouponRequest) (*UseCouponReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UseCoupon not implemented")
}
func (UnimplementedMarketingServer) GetCouponStats(context.Context, *GetCouponStatsRequest) (*GetCouponStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCouponStats not implemented")
}
func (UnimplementedMarketingServer) ListCouponUsages(context.Context, *ListCouponUsagesRequest) (*ListCouponUsagesReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCouponUsages not implemented")
}
func (UnimplementedMarketingServer) GetCouponsSummaryStats(context.Context, *GetCouponsSummaryStatsRequest) (*GetCouponsSummaryStatsReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCouponsSummaryStats not implemented")
}
func (UnimplementedMarketingServer) mustEmbedUnimplementedMarketingServer() {}
func (UnimplementedMarketingServer) testEmbeddedByValue()                   {}

// UnsafeMarketingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketingServer will
// result in compilation errors.
type UnsafeMarketingServer interface {
	mustEmbedUnimplementedMarketingServer()
}

func RegisterMarketingServer(s grpc.ServiceRegistrar, srv MarketingServer) {
	// If the following call panics, it indicates UnimplementedMarketingServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Marketing_ServiceDesc, srv)
}

func _Marketing_CreateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).CreateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_CreateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).CreateCoupon(ctx, req.(*CreateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetCoupon(ctx, req.(*GetCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListCoupons(ctx, req.(*ListCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_UpdateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).UpdateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_UpdateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).UpdateCoupon(ctx, req.(*UpdateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_DeleteCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).DeleteCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_DeleteCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).DeleteCoupon(ctx, req.(*DeleteCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ValidateCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ValidateCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ValidateCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ValidateCoupon(ctx, req.(*ValidateCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_UseCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).UseCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_UseCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).UseCoupon(ctx, req.(*UseCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetCouponStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCouponStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetCouponStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetCouponStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetCouponStats(ctx, req.(*GetCouponStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_ListCouponUsages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponUsagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).ListCouponUsages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_ListCouponUsages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).ListCouponUsages(ctx, req.(*ListCouponUsagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Marketing_GetCouponsSummaryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCouponsSummaryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketingServer).GetCouponsSummaryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Marketing_GetCouponsSummaryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketingServer).GetCouponsSummaryStats(ctx, req.(*GetCouponsSummaryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Marketing_ServiceDesc is the grpc.ServiceDesc for Marketing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Marketing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "platform.marketing_service.v1.Marketing",
	HandlerType: (*MarketingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCoupon",
			Handler:    _Marketing_CreateCoupon_Handler,
		},
		{
			MethodName: "GetCoupon",
			Handler:    _Marketing_GetCoupon_Handler,
		},
		{
			MethodName: "ListCoupons",
			Handler:    _Marketing_ListCoupons_Handler,
		},
		{
			MethodName: "UpdateCoupon",
			Handler:    _Marketing_UpdateCoupon_Handler,
		},
		{
			MethodName: "DeleteCoupon",
			Handler:    _Marketing_DeleteCoupon_Handler,
		},
		{
			MethodName: "ValidateCoupon",
			Handler:    _Marketing_ValidateCoupon_Handler,
		},
		{
			MethodName: "UseCoupon",
			Handler:    _Marketing_UseCoupon_Handler,
		},
		{
			MethodName: "GetCouponStats",
			Handler:    _Marketing_GetCouponStats_Handler,
		},
		{
			MethodName: "ListCouponUsages",
			Handler:    _Marketing_ListCouponUsages_Handler,
		},
		{
			MethodName: "GetCouponsSummaryStats",
			Handler:    _Marketing_GetCouponsSummaryStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "marketing.proto",
}
