// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: platform/marketing_service/v1/marketing.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Campaign with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Campaign) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Campaign with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CampaignMultiError, or nil
// if none found.
func (m *Campaign) ValidateAll() error {
	return m.validate(true)
}

func (m *Campaign) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CampaignId

	// no validation rules for CampaignName

	// no validation rules for TenantId

	// no validation rules for ProductCode

	// no validation rules for CampaignType

	// no validation rules for StartTime

	// no validation rules for EndTime

	// no validation rules for TotalBudget

	// no validation rules for RuleConfig

	// no validation rules for Status

	// no validation rules for CreatedBy

	// no validation rules for CreatedAt

	// no validation rules for UpdatedAt

	if len(errors) > 0 {
		return CampaignMultiError(errors)
	}

	return nil
}

// CampaignMultiError is an error wrapping multiple validation errors returned
// by Campaign.ValidateAll() if the designated constraints aren't met.
type CampaignMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CampaignMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CampaignMultiError) AllErrors() []error { return m }

// CampaignValidationError is the validation error returned by
// Campaign.Validate if the designated constraints aren't met.
type CampaignValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CampaignValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CampaignValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CampaignValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CampaignValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CampaignValidationError) ErrorName() string { return "CampaignValidationError" }

// Error satisfies the builtin error interface
func (e CampaignValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCampaign.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CampaignValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CampaignValidationError{}

// Validate checks the field values on RedeemCode with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *RedeemCode) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedeemCode with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in RedeemCodeMultiError, or
// nil if none found.
func (m *RedeemCode) ValidateAll() error {
	return m.validate(true)
}

func (m *RedeemCode) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RedeemCodeId

	// no validation rules for Code

	// no validation rules for CampaignId

	// no validation rules for TenantId

	// no validation rules for ProductCode

	// no validation rules for CodeType

	// no validation rules for UserId

	// no validation rules for Status

	// no validation rules for ValueAmount

	// no validation rules for ValuePercent

	// no validation rules for RewardItems

	if all {
		switch v := interface{}(m.GetValidFrom()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RedeemCodeValidationError{
					field:  "ValidFrom",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RedeemCodeValidationError{
					field:  "ValidFrom",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetValidFrom()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RedeemCodeValidationError{
				field:  "ValidFrom",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetValidUntil()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RedeemCodeValidationError{
					field:  "ValidUntil",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RedeemCodeValidationError{
					field:  "ValidUntil",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetValidUntil()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RedeemCodeValidationError{
				field:  "ValidUntil",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetRedemptionAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RedeemCodeValidationError{
					field:  "RedemptionAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RedeemCodeValidationError{
					field:  "RedemptionAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRedemptionAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RedeemCodeValidationError{
				field:  "RedemptionAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for RedeemChannel

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RedeemCodeValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RedeemCodeValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RedeemCodeValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RedeemCodeValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RedeemCodeValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RedeemCodeValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RedeemCodeMultiError(errors)
	}

	return nil
}

// RedeemCodeMultiError is an error wrapping multiple validation errors
// returned by RedeemCode.ValidateAll() if the designated constraints aren't met.
type RedeemCodeMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedeemCodeMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedeemCodeMultiError) AllErrors() []error { return m }

// RedeemCodeValidationError is the validation error returned by
// RedeemCode.Validate if the designated constraints aren't met.
type RedeemCodeValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedeemCodeValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedeemCodeValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedeemCodeValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedeemCodeValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedeemCodeValidationError) ErrorName() string { return "RedeemCodeValidationError" }

// Error satisfies the builtin error interface
func (e RedeemCodeValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedeemCode.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedeemCodeValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedeemCodeValidationError{}

// Validate checks the field values on CodeBatch with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CodeBatch) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CodeBatch with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CodeBatchMultiError, or nil
// if none found.
func (m *CodeBatch) ValidateAll() error {
	return m.validate(true)
}

func (m *CodeBatch) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BatchId

	// no validation rules for CampaignId

	// no validation rules for TenantId

	// no validation rules for GenerateType

	// no validation rules for TotalCount

	// no validation rules for UsedCount

	// no validation rules for Operator

	// no validation rules for GenerateRule

	// no validation rules for CreatedAt

	if len(errors) > 0 {
		return CodeBatchMultiError(errors)
	}

	return nil
}

// CodeBatchMultiError is an error wrapping multiple validation errors returned
// by CodeBatch.ValidateAll() if the designated constraints aren't met.
type CodeBatchMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CodeBatchMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CodeBatchMultiError) AllErrors() []error { return m }

// CodeBatchValidationError is the validation error returned by
// CodeBatch.Validate if the designated constraints aren't met.
type CodeBatchValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CodeBatchValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CodeBatchValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CodeBatchValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CodeBatchValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CodeBatchValidationError) ErrorName() string { return "CodeBatchValidationError" }

// Error satisfies the builtin error interface
func (e CodeBatchValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCodeBatch.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CodeBatchValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CodeBatchValidationError{}

// Validate checks the field values on RedemptionRecord with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RedemptionRecord) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedemptionRecord with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RedemptionRecordMultiError, or nil if none found.
func (m *RedemptionRecord) ValidateAll() error {
	return m.validate(true)
}

func (m *RedemptionRecord) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RecordId

	// no validation rules for RedeemCodeId

	// no validation rules for Code

	// no validation rules for UserId

	// no validation rules for TenantId

	// no validation rules for CampaignId

	// no validation rules for ProductCode

	// no validation rules for RedeemChannel

	// no validation rules for RedeemTime

	// no validation rules for DeviceInfo

	// no validation rules for IpAddress

	// no validation rules for Location

	// no validation rules for OrderId

	// no validation rules for RewardDetail

	if len(errors) > 0 {
		return RedemptionRecordMultiError(errors)
	}

	return nil
}

// RedemptionRecordMultiError is an error wrapping multiple validation errors
// returned by RedemptionRecord.ValidateAll() if the designated constraints
// aren't met.
type RedemptionRecordMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedemptionRecordMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedemptionRecordMultiError) AllErrors() []error { return m }

// RedemptionRecordValidationError is the validation error returned by
// RedemptionRecord.Validate if the designated constraints aren't met.
type RedemptionRecordValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedemptionRecordValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedemptionRecordValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedemptionRecordValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedemptionRecordValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedemptionRecordValidationError) ErrorName() string { return "RedemptionRecordValidationError" }

// Error satisfies the builtin error interface
func (e RedemptionRecordValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedemptionRecord.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedemptionRecordValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedemptionRecordValidationError{}

// Validate checks the field values on CreateCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateCampaignRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCampaignRequestMultiError, or nil if none found.
func (m *CreateCampaignRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCampaignRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if l := utf8.RuneCountInString(m.GetCampaignName()); l < 1 || l > 64 {
		err := CreateCampaignRequestValidationError{
			field:  "CampaignName",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetTenantId()) < 1 {
		err := CreateCampaignRequestValidationError{
			field:  "TenantId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetProductCode()) < 1 {
		err := CreateCampaignRequestValidationError{
			field:  "ProductCode",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCampaignType()) < 1 {
		err := CreateCampaignRequestValidationError{
			field:  "CampaignType",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetStartTime()) < 1 {
		err := CreateCampaignRequestValidationError{
			field:  "StartTime",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetEndTime()) < 1 {
		err := CreateCampaignRequestValidationError{
			field:  "EndTime",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for TotalBudget

	// no validation rules for RuleConfig

	// no validation rules for CreatedBy

	if len(errors) > 0 {
		return CreateCampaignRequestMultiError(errors)
	}

	return nil
}

// CreateCampaignRequestMultiError is an error wrapping multiple validation
// errors returned by CreateCampaignRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateCampaignRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCampaignRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCampaignRequestMultiError) AllErrors() []error { return m }

// CreateCampaignRequestValidationError is the validation error returned by
// CreateCampaignRequest.Validate if the designated constraints aren't met.
type CreateCampaignRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCampaignRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCampaignRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCampaignRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCampaignRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCampaignRequestValidationError) ErrorName() string {
	return "CreateCampaignRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCampaignRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCampaignRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCampaignRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCampaignRequestValidationError{}

// Validate checks the field values on CreateCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateCampaignReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateCampaignReplyMultiError, or nil if none found.
func (m *CreateCampaignReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateCampaignReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCampaign()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateCampaignReplyValidationError{
					field:  "Campaign",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateCampaignReplyValidationError{
					field:  "Campaign",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCampaign()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateCampaignReplyValidationError{
				field:  "Campaign",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateCampaignReplyMultiError(errors)
	}

	return nil
}

// CreateCampaignReplyMultiError is an error wrapping multiple validation
// errors returned by CreateCampaignReply.ValidateAll() if the designated
// constraints aren't met.
type CreateCampaignReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateCampaignReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateCampaignReplyMultiError) AllErrors() []error { return m }

// CreateCampaignReplyValidationError is the validation error returned by
// CreateCampaignReply.Validate if the designated constraints aren't met.
type CreateCampaignReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateCampaignReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateCampaignReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateCampaignReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateCampaignReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateCampaignReplyValidationError) ErrorName() string {
	return "CreateCampaignReplyValidationError"
}

// Error satisfies the builtin error interface
func (e CreateCampaignReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateCampaignReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateCampaignReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateCampaignReplyValidationError{}

// Validate checks the field values on GetCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCampaignRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCampaignRequestMultiError, or nil if none found.
func (m *GetCampaignRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCampaignRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCampaignId()) < 1 {
		err := GetCampaignRequestValidationError{
			field:  "CampaignId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetCampaignRequestMultiError(errors)
	}

	return nil
}

// GetCampaignRequestMultiError is an error wrapping multiple validation errors
// returned by GetCampaignRequest.ValidateAll() if the designated constraints
// aren't met.
type GetCampaignRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCampaignRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCampaignRequestMultiError) AllErrors() []error { return m }

// GetCampaignRequestValidationError is the validation error returned by
// GetCampaignRequest.Validate if the designated constraints aren't met.
type GetCampaignRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCampaignRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCampaignRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCampaignRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCampaignRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCampaignRequestValidationError) ErrorName() string {
	return "GetCampaignRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCampaignRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCampaignRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCampaignRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCampaignRequestValidationError{}

// Validate checks the field values on GetCampaignReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetCampaignReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCampaignReplyMultiError, or nil if none found.
func (m *GetCampaignReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCampaignReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCampaign()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetCampaignReplyValidationError{
					field:  "Campaign",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetCampaignReplyValidationError{
					field:  "Campaign",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCampaign()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetCampaignReplyValidationError{
				field:  "Campaign",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetCampaignReplyMultiError(errors)
	}

	return nil
}

// GetCampaignReplyMultiError is an error wrapping multiple validation errors
// returned by GetCampaignReply.ValidateAll() if the designated constraints
// aren't met.
type GetCampaignReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCampaignReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCampaignReplyMultiError) AllErrors() []error { return m }

// GetCampaignReplyValidationError is the validation error returned by
// GetCampaignReply.Validate if the designated constraints aren't met.
type GetCampaignReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCampaignReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCampaignReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCampaignReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCampaignReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCampaignReplyValidationError) ErrorName() string { return "GetCampaignReplyValidationError" }

// Error satisfies the builtin error interface
func (e GetCampaignReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCampaignReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCampaignReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCampaignReplyValidationError{}

// Validate checks the field values on ListCampaignsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCampaignsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCampaignsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCampaignsRequestMultiError, or nil if none found.
func (m *ListCampaignsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCampaignsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for TenantId

	// no validation rules for ProductCode

	// no validation rules for CampaignType

	// no validation rules for Status

	// no validation rules for PageSize

	// no validation rules for PageNum

	if len(errors) > 0 {
		return ListCampaignsRequestMultiError(errors)
	}

	return nil
}

// ListCampaignsRequestMultiError is an error wrapping multiple validation
// errors returned by ListCampaignsRequest.ValidateAll() if the designated
// constraints aren't met.
type ListCampaignsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCampaignsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCampaignsRequestMultiError) AllErrors() []error { return m }

// ListCampaignsRequestValidationError is the validation error returned by
// ListCampaignsRequest.Validate if the designated constraints aren't met.
type ListCampaignsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCampaignsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCampaignsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCampaignsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCampaignsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCampaignsRequestValidationError) ErrorName() string {
	return "ListCampaignsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListCampaignsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCampaignsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCampaignsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCampaignsRequestValidationError{}

// Validate checks the field values on ListCampaignsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListCampaignsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListCampaignsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListCampaignsReplyMultiError, or nil if none found.
func (m *ListCampaignsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListCampaignsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetCampaigns() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListCampaignsReplyValidationError{
						field:  fmt.Sprintf("Campaigns[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListCampaignsReplyValidationError{
						field:  fmt.Sprintf("Campaigns[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListCampaignsReplyValidationError{
					field:  fmt.Sprintf("Campaigns[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListCampaignsReplyMultiError(errors)
	}

	return nil
}

// ListCampaignsReplyMultiError is an error wrapping multiple validation errors
// returned by ListCampaignsReply.ValidateAll() if the designated constraints
// aren't met.
type ListCampaignsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListCampaignsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListCampaignsReplyMultiError) AllErrors() []error { return m }

// ListCampaignsReplyValidationError is the validation error returned by
// ListCampaignsReply.Validate if the designated constraints aren't met.
type ListCampaignsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListCampaignsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListCampaignsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListCampaignsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListCampaignsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListCampaignsReplyValidationError) ErrorName() string {
	return "ListCampaignsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListCampaignsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListCampaignsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListCampaignsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListCampaignsReplyValidationError{}

// Validate checks the field values on UpdateCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateCampaignRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateCampaignRequestMultiError, or nil if none found.
func (m *UpdateCampaignRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateCampaignRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCampaignId()) < 1 {
		err := UpdateCampaignRequestValidationError{
			field:  "CampaignId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if l := utf8.RuneCountInString(m.GetCampaignName()); l < 1 || l > 64 {
		err := UpdateCampaignRequestValidationError{
			field:  "CampaignName",
			reason: "value length must be between 1 and 64 runes, inclusive",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for StartTime

	// no validation rules for EndTime

	// no validation rules for TotalBudget

	// no validation rules for RuleConfig

	// no validation rules for Status

	if len(errors) > 0 {
		return UpdateCampaignRequestMultiError(errors)
	}

	return nil
}

// UpdateCampaignRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateCampaignRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateCampaignRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateCampaignRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateCampaignRequestMultiError) AllErrors() []error { return m }

// UpdateCampaignRequestValidationError is the validation error returned by
// UpdateCampaignRequest.Validate if the designated constraints aren't met.
type UpdateCampaignRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateCampaignRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateCampaignRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateCampaignRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateCampaignRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateCampaignRequestValidationError) ErrorName() string {
	return "UpdateCampaignRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateCampaignRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateCampaignRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateCampaignRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateCampaignRequestValidationError{}

// Validate checks the field values on UpdateCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateCampaignReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateCampaignReplyMultiError, or nil if none found.
func (m *UpdateCampaignReply) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateCampaignReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCampaign()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateCampaignReplyValidationError{
					field:  "Campaign",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateCampaignReplyValidationError{
					field:  "Campaign",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCampaign()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateCampaignReplyValidationError{
				field:  "Campaign",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateCampaignReplyMultiError(errors)
	}

	return nil
}

// UpdateCampaignReplyMultiError is an error wrapping multiple validation
// errors returned by UpdateCampaignReply.ValidateAll() if the designated
// constraints aren't met.
type UpdateCampaignReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateCampaignReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateCampaignReplyMultiError) AllErrors() []error { return m }

// UpdateCampaignReplyValidationError is the validation error returned by
// UpdateCampaignReply.Validate if the designated constraints aren't met.
type UpdateCampaignReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateCampaignReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateCampaignReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateCampaignReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateCampaignReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateCampaignReplyValidationError) ErrorName() string {
	return "UpdateCampaignReplyValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateCampaignReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateCampaignReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateCampaignReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateCampaignReplyValidationError{}

// Validate checks the field values on DeleteCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteCampaignRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteCampaignRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteCampaignRequestMultiError, or nil if none found.
func (m *DeleteCampaignRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteCampaignRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCampaignId()) < 1 {
		err := DeleteCampaignRequestValidationError{
			field:  "CampaignId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return DeleteCampaignRequestMultiError(errors)
	}

	return nil
}

// DeleteCampaignRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteCampaignRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteCampaignRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteCampaignRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteCampaignRequestMultiError) AllErrors() []error { return m }

// DeleteCampaignRequestValidationError is the validation error returned by
// DeleteCampaignRequest.Validate if the designated constraints aren't met.
type DeleteCampaignRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteCampaignRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteCampaignRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteCampaignRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteCampaignRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteCampaignRequestValidationError) ErrorName() string {
	return "DeleteCampaignRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteCampaignRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteCampaignRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteCampaignRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteCampaignRequestValidationError{}

// Validate checks the field values on DeleteCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteCampaignReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteCampaignReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteCampaignReplyMultiError, or nil if none found.
func (m *DeleteCampaignReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteCampaignReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	if len(errors) > 0 {
		return DeleteCampaignReplyMultiError(errors)
	}

	return nil
}

// DeleteCampaignReplyMultiError is an error wrapping multiple validation
// errors returned by DeleteCampaignReply.ValidateAll() if the designated
// constraints aren't met.
type DeleteCampaignReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteCampaignReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteCampaignReplyMultiError) AllErrors() []error { return m }

// DeleteCampaignReplyValidationError is the validation error returned by
// DeleteCampaignReply.Validate if the designated constraints aren't met.
type DeleteCampaignReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteCampaignReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteCampaignReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteCampaignReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteCampaignReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteCampaignReplyValidationError) ErrorName() string {
	return "DeleteCampaignReplyValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteCampaignReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteCampaignReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteCampaignReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteCampaignReplyValidationError{}

// Validate checks the field values on GenerateRedeemCodesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateRedeemCodesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateRedeemCodesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateRedeemCodesRequestMultiError, or nil if none found.
func (m *GenerateRedeemCodesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateRedeemCodesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCampaignId()) < 1 {
		err := GenerateRedeemCodesRequestValidationError{
			field:  "CampaignId",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetCodeType()) < 1 {
		err := GenerateRedeemCodesRequestValidationError{
			field:  "CodeType",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetCount() <= 0 {
		err := GenerateRedeemCodesRequestValidationError{
			field:  "Count",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetGenerateType()) < 1 {
		err := GenerateRedeemCodesRequestValidationError{
			field:  "GenerateType",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for GenerateRule

	// no validation rules for ValueAmount

	// no validation rules for ValuePercent

	// no validation rules for RewardItems

	// no validation rules for ExpireTime

	// no validation rules for Operator

	if len(errors) > 0 {
		return GenerateRedeemCodesRequestMultiError(errors)
	}

	return nil
}

// GenerateRedeemCodesRequestMultiError is an error wrapping multiple
// validation errors returned by GenerateRedeemCodesRequest.ValidateAll() if
// the designated constraints aren't met.
type GenerateRedeemCodesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateRedeemCodesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateRedeemCodesRequestMultiError) AllErrors() []error { return m }

// GenerateRedeemCodesRequestValidationError is the validation error returned
// by GenerateRedeemCodesRequest.Validate if the designated constraints aren't met.
type GenerateRedeemCodesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateRedeemCodesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateRedeemCodesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateRedeemCodesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateRedeemCodesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateRedeemCodesRequestValidationError) ErrorName() string {
	return "GenerateRedeemCodesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateRedeemCodesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateRedeemCodesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateRedeemCodesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateRedeemCodesRequestValidationError{}

// Validate checks the field values on GenerateRedeemCodesReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateRedeemCodesReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateRedeemCodesReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateRedeemCodesReplyMultiError, or nil if none found.
func (m *GenerateRedeemCodesReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateRedeemCodesReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BatchId

	// no validation rules for TotalCount

	if len(errors) > 0 {
		return GenerateRedeemCodesReplyMultiError(errors)
	}

	return nil
}

// GenerateRedeemCodesReplyMultiError is an error wrapping multiple validation
// errors returned by GenerateRedeemCodesReply.ValidateAll() if the designated
// constraints aren't met.
type GenerateRedeemCodesReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateRedeemCodesReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateRedeemCodesReplyMultiError) AllErrors() []error { return m }

// GenerateRedeemCodesReplyValidationError is the validation error returned by
// GenerateRedeemCodesReply.Validate if the designated constraints aren't met.
type GenerateRedeemCodesReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateRedeemCodesReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateRedeemCodesReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateRedeemCodesReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateRedeemCodesReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateRedeemCodesReplyValidationError) ErrorName() string {
	return "GenerateRedeemCodesReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateRedeemCodesReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateRedeemCodesReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateRedeemCodesReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateRedeemCodesReplyValidationError{}

// Validate checks the field values on RedeemCodeRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RedeemCodeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedeemCodeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RedeemCodeRequestMultiError, or nil if none found.
func (m *RedeemCodeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RedeemCodeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCode()) < 1 {
		err := RedeemCodeRequestValidationError{
			field:  "Code",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := RedeemCodeRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetProductCode()) < 1 {
		err := RedeemCodeRequestValidationError{
			field:  "ProductCode",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for RedeemChannel

	// no validation rules for DeviceInfo

	// no validation rules for IpAddress

	// no validation rules for Location

	// no validation rules for OrderId

	if len(errors) > 0 {
		return RedeemCodeRequestMultiError(errors)
	}

	return nil
}

// RedeemCodeRequestMultiError is an error wrapping multiple validation errors
// returned by RedeemCodeRequest.ValidateAll() if the designated constraints
// aren't met.
type RedeemCodeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedeemCodeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedeemCodeRequestMultiError) AllErrors() []error { return m }

// RedeemCodeRequestValidationError is the validation error returned by
// RedeemCodeRequest.Validate if the designated constraints aren't met.
type RedeemCodeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedeemCodeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedeemCodeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedeemCodeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedeemCodeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedeemCodeRequestValidationError) ErrorName() string {
	return "RedeemCodeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RedeemCodeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedeemCodeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedeemCodeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedeemCodeRequestValidationError{}

// Validate checks the field values on RedeemCodeReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RedeemCodeReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RedeemCodeReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RedeemCodeReplyMultiError, or nil if none found.
func (m *RedeemCodeReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RedeemCodeReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	// no validation rules for RewardDetail

	if all {
		switch v := interface{}(m.GetCodeInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RedeemCodeReplyValidationError{
					field:  "CodeInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RedeemCodeReplyValidationError{
					field:  "CodeInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCodeInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RedeemCodeReplyValidationError{
				field:  "CodeInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RedeemCodeReplyMultiError(errors)
	}

	return nil
}

// RedeemCodeReplyMultiError is an error wrapping multiple validation errors
// returned by RedeemCodeReply.ValidateAll() if the designated constraints
// aren't met.
type RedeemCodeReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RedeemCodeReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RedeemCodeReplyMultiError) AllErrors() []error { return m }

// RedeemCodeReplyValidationError is the validation error returned by
// RedeemCodeReply.Validate if the designated constraints aren't met.
type RedeemCodeReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RedeemCodeReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RedeemCodeReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RedeemCodeReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RedeemCodeReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RedeemCodeReplyValidationError) ErrorName() string { return "RedeemCodeReplyValidationError" }

// Error satisfies the builtin error interface
func (e RedeemCodeReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRedeemCodeReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RedeemCodeReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RedeemCodeReplyValidationError{}

// Validate checks the field values on AssignRedeemCodeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AssignRedeemCodeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AssignRedeemCodeRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AssignRedeemCodeRequestMultiError, or nil if none found.
func (m *AssignRedeemCodeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AssignRedeemCodeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCode()) < 1 {
		err := AssignRedeemCodeRequestValidationError{
			field:  "Code",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetUserId() <= 0 {
		err := AssignRedeemCodeRequestValidationError{
			field:  "UserId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return AssignRedeemCodeRequestMultiError(errors)
	}

	return nil
}

// AssignRedeemCodeRequestMultiError is an error wrapping multiple validation
// errors returned by AssignRedeemCodeRequest.ValidateAll() if the designated
// constraints aren't met.
type AssignRedeemCodeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AssignRedeemCodeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AssignRedeemCodeRequestMultiError) AllErrors() []error { return m }

// AssignRedeemCodeRequestValidationError is the validation error returned by
// AssignRedeemCodeRequest.Validate if the designated constraints aren't met.
type AssignRedeemCodeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AssignRedeemCodeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AssignRedeemCodeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AssignRedeemCodeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AssignRedeemCodeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AssignRedeemCodeRequestValidationError) ErrorName() string {
	return "AssignRedeemCodeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AssignRedeemCodeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAssignRedeemCodeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AssignRedeemCodeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AssignRedeemCodeRequestValidationError{}

// Validate checks the field values on AssignRedeemCodeReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AssignRedeemCodeReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AssignRedeemCodeReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AssignRedeemCodeReplyMultiError, or nil if none found.
func (m *AssignRedeemCodeReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AssignRedeemCodeReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	if all {
		switch v := interface{}(m.GetCodeInfo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AssignRedeemCodeReplyValidationError{
					field:  "CodeInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AssignRedeemCodeReplyValidationError{
					field:  "CodeInfo",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCodeInfo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AssignRedeemCodeReplyValidationError{
				field:  "CodeInfo",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AssignRedeemCodeReplyMultiError(errors)
	}

	return nil
}

// AssignRedeemCodeReplyMultiError is an error wrapping multiple validation
// errors returned by AssignRedeemCodeReply.ValidateAll() if the designated
// constraints aren't met.
type AssignRedeemCodeReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AssignRedeemCodeReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AssignRedeemCodeReplyMultiError) AllErrors() []error { return m }

// AssignRedeemCodeReplyValidationError is the validation error returned by
// AssignRedeemCodeReply.Validate if the designated constraints aren't met.
type AssignRedeemCodeReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AssignRedeemCodeReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AssignRedeemCodeReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AssignRedeemCodeReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AssignRedeemCodeReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AssignRedeemCodeReplyValidationError) ErrorName() string {
	return "AssignRedeemCodeReplyValidationError"
}

// Error satisfies the builtin error interface
func (e AssignRedeemCodeReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAssignRedeemCodeReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AssignRedeemCodeReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AssignRedeemCodeReplyValidationError{}

// Validate checks the field values on ListRedeemCodesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRedeemCodesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRedeemCodesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRedeemCodesRequestMultiError, or nil if none found.
func (m *ListRedeemCodesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRedeemCodesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CampaignId

	// no validation rules for TenantId

	// no validation rules for ProductCode

	// no validation rules for CodeType

	// no validation rules for Status

	// no validation rules for UserId

	// no validation rules for PageSize

	// no validation rules for PageNum

	if len(errors) > 0 {
		return ListRedeemCodesRequestMultiError(errors)
	}

	return nil
}

// ListRedeemCodesRequestMultiError is an error wrapping multiple validation
// errors returned by ListRedeemCodesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListRedeemCodesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRedeemCodesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRedeemCodesRequestMultiError) AllErrors() []error { return m }

// ListRedeemCodesRequestValidationError is the validation error returned by
// ListRedeemCodesRequest.Validate if the designated constraints aren't met.
type ListRedeemCodesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRedeemCodesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRedeemCodesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRedeemCodesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRedeemCodesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRedeemCodesRequestValidationError) ErrorName() string {
	return "ListRedeemCodesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRedeemCodesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRedeemCodesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRedeemCodesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRedeemCodesRequestValidationError{}

// Validate checks the field values on ListRedeemCodesReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRedeemCodesReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRedeemCodesReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRedeemCodesReplyMultiError, or nil if none found.
func (m *ListRedeemCodesReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRedeemCodesReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetCodes() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRedeemCodesReplyValidationError{
						field:  fmt.Sprintf("Codes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRedeemCodesReplyValidationError{
						field:  fmt.Sprintf("Codes[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRedeemCodesReplyValidationError{
					field:  fmt.Sprintf("Codes[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	if len(errors) > 0 {
		return ListRedeemCodesReplyMultiError(errors)
	}

	return nil
}

// ListRedeemCodesReplyMultiError is an error wrapping multiple validation
// errors returned by ListRedeemCodesReply.ValidateAll() if the designated
// constraints aren't met.
type ListRedeemCodesReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRedeemCodesReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRedeemCodesReplyMultiError) AllErrors() []error { return m }

// ListRedeemCodesReplyValidationError is the validation error returned by
// ListRedeemCodesReply.Validate if the designated constraints aren't met.
type ListRedeemCodesReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRedeemCodesReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRedeemCodesReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRedeemCodesReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRedeemCodesReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRedeemCodesReplyValidationError) ErrorName() string {
	return "ListRedeemCodesReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ListRedeemCodesReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRedeemCodesReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRedeemCodesReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRedeemCodesReplyValidationError{}

// Validate checks the field values on GetRedeemCodeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRedeemCodeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRedeemCodeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRedeemCodeRequestMultiError, or nil if none found.
func (m *GetRedeemCodeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRedeemCodeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetCode()) < 1 {
		err := GetRedeemCodeRequestValidationError{
			field:  "Code",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetRedeemCodeRequestMultiError(errors)
	}

	return nil
}

// GetRedeemCodeRequestMultiError is an error wrapping multiple validation
// errors returned by GetRedeemCodeRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRedeemCodeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRedeemCodeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRedeemCodeRequestMultiError) AllErrors() []error { return m }

// GetRedeemCodeRequestValidationError is the validation error returned by
// GetRedeemCodeRequest.Validate if the designated constraints aren't met.
type GetRedeemCodeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRedeemCodeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRedeemCodeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRedeemCodeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRedeemCodeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRedeemCodeRequestValidationError) ErrorName() string {
	return "GetRedeemCodeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRedeemCodeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRedeemCodeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRedeemCodeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRedeemCodeRequestValidationError{}

// Validate checks the field values on GetRedeemCodeReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRedeemCodeReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRedeemCodeReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRedeemCodeReplyMultiError, or nil if none found.
func (m *GetRedeemCodeReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRedeemCodeReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCode()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetRedeemCodeReplyValidationError{
					field:  "Code",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetRedeemCodeReplyValidationError{
					field:  "Code",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCode()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetRedeemCodeReplyValidationError{
				field:  "Code",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetRedeemCodeReplyMultiError(errors)
	}

	return nil
}

// GetRedeemCodeReplyMultiError is an error wrapping multiple validation errors
// returned by GetRedeemCodeReply.ValidateAll() if the designated constraints
// aren't met.
type GetRedeemCodeReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRedeemCodeReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRedeemCodeReplyMultiError) AllErrors() []error { return m }

// GetRedeemCodeReplyValidationError is the validation error returned by
// GetRedeemCodeReply.Validate if the designated constraints aren't met.
type GetRedeemCodeReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRedeemCodeReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRedeemCodeReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRedeemCodeReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRedeemCodeReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRedeemCodeReplyValidationError) ErrorName() string {
	return "GetRedeemCodeReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetRedeemCodeReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRedeemCodeReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRedeemCodeReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRedeemCodeReplyValidationError{}
