// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.4
// - protoc             v5.29.3
// source: platform/marketing_service/v1/marketing.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationMarketingAssignRedeemCode = "/platform.marketing_service.v1.Marketing/AssignRedeemCode"
const OperationMarketingCreateCampaign = "/platform.marketing_service.v1.Marketing/CreateCampaign"
const OperationMarketingDeleteCampaign = "/platform.marketing_service.v1.Marketing/DeleteCampaign"
const OperationMarketingGenerateRedeemCodes = "/platform.marketing_service.v1.Marketing/GenerateRedeemCodes"
const OperationMarketingGetCampaign = "/platform.marketing_service.v1.Marketing/GetCampaign"
const OperationMarketingGetRedeemCode = "/platform.marketing_service.v1.Marketing/GetRedeemCode"
const OperationMarketingListCampaigns = "/platform.marketing_service.v1.Marketing/ListCampaigns"
const OperationMarketingListRedeemCodes = "/platform.marketing_service.v1.Marketing/ListRedeemCodes"
const OperationMarketingRedeemCode = "/platform.marketing_service.v1.Marketing/RedeemCode"
const OperationMarketingUpdateCampaign = "/platform.marketing_service.v1.Marketing/UpdateCampaign"

type MarketingHTTPServer interface {
	// AssignRedeemCode AssignRedeemCode 分配兑换码
	AssignRedeemCode(context.Context, *AssignRedeemCodeRequest) (*AssignRedeemCodeReply, error)
	// CreateCampaign CreateCampaign 创建营销活动
	CreateCampaign(context.Context, *CreateCampaignRequest) (*CreateCampaignReply, error)
	// DeleteCampaign DeleteCampaign 删除营销活动
	DeleteCampaign(context.Context, *DeleteCampaignRequest) (*DeleteCampaignReply, error)
	// GenerateRedeemCodes GenerateRedeemCodes 生成兑换码
	GenerateRedeemCodes(context.Context, *GenerateRedeemCodesRequest) (*GenerateRedeemCodesReply, error)
	// GetCampaign GetCampaign 获取营销活动
	GetCampaign(context.Context, *GetCampaignRequest) (*GetCampaignReply, error)
	// GetRedeemCode GetRedeemCode 获取兑换码
	GetRedeemCode(context.Context, *GetRedeemCodeRequest) (*GetRedeemCodeReply, error)
	// ListCampaigns ListCampaigns 列出营销活动
	ListCampaigns(context.Context, *ListCampaignsRequest) (*ListCampaignsReply, error)
	// ListRedeemCodes ListRedeemCodes 列出兑换码
	ListRedeemCodes(context.Context, *ListRedeemCodesRequest) (*ListRedeemCodesReply, error)
	// RedeemCode RedeemCode 兑换码核销
	RedeemCode(context.Context, *RedeemCodeRequest) (*RedeemCodeReply, error)
	// UpdateCampaign UpdateCampaign 更新营销活动
	UpdateCampaign(context.Context, *UpdateCampaignRequest) (*UpdateCampaignReply, error)
}

func RegisterMarketingHTTPServer(s *http.Server, srv MarketingHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/campaigns", _Marketing_CreateCampaign0_HTTP_Handler(srv))
	r.GET("/v1/campaigns/{campaign_id}", _Marketing_GetCampaign0_HTTP_Handler(srv))
	r.GET("/v1/campaigns", _Marketing_ListCampaigns0_HTTP_Handler(srv))
	r.PUT("/v1/campaigns/{campaign_id}", _Marketing_UpdateCampaign0_HTTP_Handler(srv))
	r.DELETE("/v1/campaigns/{campaign_id}", _Marketing_DeleteCampaign0_HTTP_Handler(srv))
	r.POST("/v1/campaigns/{campaign_id}/redeem-codes", _Marketing_GenerateRedeemCodes0_HTTP_Handler(srv))
	r.POST("/v1/redeem", _Marketing_RedeemCode0_HTTP_Handler(srv))
	r.POST("/v1/redeem-codes/{code}/assign", _Marketing_AssignRedeemCode0_HTTP_Handler(srv))
	r.GET("/v1/redeem-codes", _Marketing_ListRedeemCodes0_HTTP_Handler(srv))
	r.GET("/v1/redeem-codes/{code}", _Marketing_GetRedeemCode0_HTTP_Handler(srv))
}

func _Marketing_CreateCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateCampaignRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingCreateCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateCampaign(ctx, req.(*CreateCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetCampaignRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetCampaign(ctx, req.(*GetCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListCampaigns0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListCampaignsRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListCampaigns)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListCampaigns(ctx, req.(*ListCampaignsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListCampaignsReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_UpdateCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateCampaignRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingUpdateCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateCampaign(ctx, req.(*UpdateCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*UpdateCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_DeleteCampaign0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteCampaignRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingDeleteCampaign)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteCampaign(ctx, req.(*DeleteCampaignRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*DeleteCampaignReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GenerateRedeemCodes0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GenerateRedeemCodesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGenerateRedeemCodes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GenerateRedeemCodes(ctx, req.(*GenerateRedeemCodesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GenerateRedeemCodesReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_RedeemCode0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in RedeemCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingRedeemCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.RedeemCode(ctx, req.(*RedeemCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RedeemCodeReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_AssignRedeemCode0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in AssignRedeemCodeRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingAssignRedeemCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.AssignRedeemCode(ctx, req.(*AssignRedeemCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AssignRedeemCodeReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_ListRedeemCodes0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRedeemCodesRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingListRedeemCodes)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRedeemCodes(ctx, req.(*ListRedeemCodesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRedeemCodesReply)
		return ctx.Result(200, reply)
	}
}

func _Marketing_GetRedeemCode0_HTTP_Handler(srv MarketingHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRedeemCodeRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationMarketingGetRedeemCode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRedeemCode(ctx, req.(*GetRedeemCodeRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*GetRedeemCodeReply)
		return ctx.Result(200, reply)
	}
}

type MarketingHTTPClient interface {
	AssignRedeemCode(ctx context.Context, req *AssignRedeemCodeRequest, opts ...http.CallOption) (rsp *AssignRedeemCodeReply, err error)
	CreateCampaign(ctx context.Context, req *CreateCampaignRequest, opts ...http.CallOption) (rsp *CreateCampaignReply, err error)
	DeleteCampaign(ctx context.Context, req *DeleteCampaignRequest, opts ...http.CallOption) (rsp *DeleteCampaignReply, err error)
	GenerateRedeemCodes(ctx context.Context, req *GenerateRedeemCodesRequest, opts ...http.CallOption) (rsp *GenerateRedeemCodesReply, err error)
	GetCampaign(ctx context.Context, req *GetCampaignRequest, opts ...http.CallOption) (rsp *GetCampaignReply, err error)
	GetRedeemCode(ctx context.Context, req *GetRedeemCodeRequest, opts ...http.CallOption) (rsp *GetRedeemCodeReply, err error)
	ListCampaigns(ctx context.Context, req *ListCampaignsRequest, opts ...http.CallOption) (rsp *ListCampaignsReply, err error)
	ListRedeemCodes(ctx context.Context, req *ListRedeemCodesRequest, opts ...http.CallOption) (rsp *ListRedeemCodesReply, err error)
	RedeemCode(ctx context.Context, req *RedeemCodeRequest, opts ...http.CallOption) (rsp *RedeemCodeReply, err error)
	UpdateCampaign(ctx context.Context, req *UpdateCampaignRequest, opts ...http.CallOption) (rsp *UpdateCampaignReply, err error)
}

type MarketingHTTPClientImpl struct {
	cc *http.Client
}

func NewMarketingHTTPClient(client *http.Client) MarketingHTTPClient {
	return &MarketingHTTPClientImpl{client}
}

func (c *MarketingHTTPClientImpl) AssignRedeemCode(ctx context.Context, in *AssignRedeemCodeRequest, opts ...http.CallOption) (*AssignRedeemCodeReply, error) {
	var out AssignRedeemCodeReply
	pattern := "/v1/redeem-codes/{code}/assign"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingAssignRedeemCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MarketingHTTPClientImpl) CreateCampaign(ctx context.Context, in *CreateCampaignRequest, opts ...http.CallOption) (*CreateCampaignReply, error) {
	var out CreateCampaignReply
	pattern := "/v1/campaigns"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingCreateCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MarketingHTTPClientImpl) DeleteCampaign(ctx context.Context, in *DeleteCampaignRequest, opts ...http.CallOption) (*DeleteCampaignReply, error) {
	var out DeleteCampaignReply
	pattern := "/v1/campaigns/{campaign_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingDeleteCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MarketingHTTPClientImpl) GenerateRedeemCodes(ctx context.Context, in *GenerateRedeemCodesRequest, opts ...http.CallOption) (*GenerateRedeemCodesReply, error) {
	var out GenerateRedeemCodesReply
	pattern := "/v1/campaigns/{campaign_id}/redeem-codes"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingGenerateRedeemCodes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MarketingHTTPClientImpl) GetCampaign(ctx context.Context, in *GetCampaignRequest, opts ...http.CallOption) (*GetCampaignReply, error) {
	var out GetCampaignReply
	pattern := "/v1/campaigns/{campaign_id}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MarketingHTTPClientImpl) GetRedeemCode(ctx context.Context, in *GetRedeemCodeRequest, opts ...http.CallOption) (*GetRedeemCodeReply, error) {
	var out GetRedeemCodeReply
	pattern := "/v1/redeem-codes/{code}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingGetRedeemCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MarketingHTTPClientImpl) ListCampaigns(ctx context.Context, in *ListCampaignsRequest, opts ...http.CallOption) (*ListCampaignsReply, error) {
	var out ListCampaignsReply
	pattern := "/v1/campaigns"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListCampaigns))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MarketingHTTPClientImpl) ListRedeemCodes(ctx context.Context, in *ListRedeemCodesRequest, opts ...http.CallOption) (*ListRedeemCodesReply, error) {
	var out ListRedeemCodesReply
	pattern := "/v1/redeem-codes"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationMarketingListRedeemCodes))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MarketingHTTPClientImpl) RedeemCode(ctx context.Context, in *RedeemCodeRequest, opts ...http.CallOption) (*RedeemCodeReply, error) {
	var out RedeemCodeReply
	pattern := "/v1/redeem"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingRedeemCode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

func (c *MarketingHTTPClientImpl) UpdateCampaign(ctx context.Context, in *UpdateCampaignRequest, opts ...http.CallOption) (*UpdateCampaignReply, error) {
	var out UpdateCampaignReply
	pattern := "/v1/campaigns/{campaign_id}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationMarketingUpdateCampaign))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
