// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/gaoyong06/middleground/marketing-service/internal/biz"
	"github.com/gaoyong06/middleground/marketing-service/internal/conf"
	"github.com/gaoyong06/middleground/marketing-service/internal/data"
	"github.com/gaoyong06/middleground/marketing-service/internal/server"
	"github.com/gaoyong06/middleground/marketing-service/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, client *conf.Client, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	redisClient := data.NewRedis(confData, logger)
	dataData, cleanup, err := data.NewData(db, redisClient, logger)
	if err != nil {
		return nil, nil, err
	}
	campaignRepo := data.NewCampaignRepo(dataData, logger)
	redeemCodeRepo := data.NewRedeemCodeRepo(dataData, logger)
	tenantServiceClient := data.NewTenantServiceClient(client, logger)
	tenantRepo := data.NewTenantRepo(dataData, tenantServiceClient, logger)
	campaignUsecase := biz.NewCampaignUsecase(campaignRepo, redeemCodeRepo, tenantRepo, logger)
	codeGenerator := biz.NewCodeGenerator(logger)
	redeemCodeUsecase := biz.NewRedeemCodeUsecase(redeemCodeRepo, campaignRepo, tenantRepo, codeGenerator, logger)
	marketingService := service.NewMarketingService(campaignUsecase, redeemCodeUsecase, logger)
	httpServer := server.NewHTTPServer(confServer, marketingService, logger)
	grpcServer := server.NewGRPCServer(confServer, marketingService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}

