// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"marketing-service/internal/biz"
	"marketing-service/internal/conf"
	"marketing-service/internal/data"
	"marketing-service/internal/server"
	"marketing-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
	_ "marketing-service/internal/errors"
)

// Injectors from wire.go:

// wireApp init kratos application.
// 极简重构：仅保留优惠券功能，移除复杂营销活动系统
func wireApp(confServer *conf.Server, confData *conf.Data, client *conf.Client, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	redisClient := data.NewRedis(confData, logger)
	dataData, cleanup, err := data.NewData(db, redisClient, logger)
	if err != nil {
		return nil, nil, err
	}
	couponRepo := data.NewCouponRepo(dataData, logger)
	couponUseCase := biz.NewCouponUseCase(couponRepo, logger)
	marketingService := service.NewMarketingService(couponUseCase, logger)
	httpServer := server.NewHTTPServer(confServer, marketingService, logger)
	grpcServer := server.NewGRPCServer(confServer, marketingService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
