// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"marketing-service/internal/biz"
	"marketing-service/internal/conf"
	"marketing-service/internal/data"
	"marketing-service/internal/server"
	"marketing-service/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
	_ "marketing-service/internal/errors"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, client *conf.Client, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	redisClient := data.NewRedis(confData, logger)
	dataData, cleanup, err := data.NewData(db, redisClient, logger)
	if err != nil {
		return nil, nil, err
	}
	cacheService := data.NewCacheService(redisClient, logger)
	campaignRepo := data.NewCampaignRepo(dataData, cacheService, logger)
	campaignUseCase := biz.NewCampaignUseCase(campaignRepo, logger)
	rewardRepo := data.NewRewardRepo(dataData, cacheService, logger)
	rewardUseCase := biz.NewRewardUseCase(rewardRepo, logger)
	rewardGrantRepo := data.NewRewardGrantRepo(dataData, logger)
	rewardGrantUseCase := biz.NewRewardGrantUseCase(rewardGrantRepo, logger)
	taskRepo := data.NewTaskRepo(dataData, cacheService, logger)
	taskUseCase := biz.NewTaskUseCase(taskRepo, logger)
	audienceRepo := data.NewAudienceRepo(dataData, logger)
	audienceUseCase := biz.NewAudienceUseCase(audienceRepo, logger)
	redeemCodeRepo := data.NewRedeemCodeRepo(dataData, logger)
	redeemCodeUseCase := biz.NewRedeemCodeUseCase(redeemCodeRepo, logger)
	inventoryReservationRepo := data.NewInventoryReservationRepo(dataData, logger)
	inventoryReservationUseCase := biz.NewInventoryReservationUseCase(inventoryReservationRepo, logger)
	taskCompletionLogRepo := data.NewTaskCompletionLogRepo(dataData, logger)
	taskCompletionLogUseCase := biz.NewTaskCompletionLogUseCase(taskCompletionLogRepo, logger)
	campaignTaskRepo := data.NewCampaignTaskRepo(dataData, logger)
	campaignTaskUseCase := biz.NewCampaignTaskUseCase(campaignTaskRepo, logger)
	audienceMatcherService := biz.NewAudienceMatcherService(audienceRepo, logger)
	validatorService := biz.NewValidatorService(audienceMatcherService, logger)
	generatorService := biz.NewGeneratorService(logger)
	notificationClient, err := data.NewNotificationClient(client, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	notificationService := biz.NewNotificationService(notificationClient, logger)
	distributorService := biz.NewDistributorService(notificationService, logger)
	producer, cleanup2, err := data.NewRocketMQProducer(confData, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	taskTriggerService := biz.NewTaskTriggerService(taskUseCase, taskCompletionLogUseCase, rewardGrantUseCase, rewardUseCase, campaignUseCase, inventoryReservationUseCase, validatorService, generatorService, distributorService, producer, logger)
	marketingService := service.NewMarketingService(campaignUseCase, rewardUseCase, rewardGrantUseCase, taskUseCase, audienceUseCase, redeemCodeUseCase, inventoryReservationUseCase, taskCompletionLogUseCase, campaignTaskUseCase, taskTriggerService, logger)
	httpServer := server.NewHTTPServer(confServer, marketingService, logger)
	grpcServer := server.NewGRPCServer(confServer, marketingService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
